// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: internal/authenticator/authenticator.proto

package authenticatorpb

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SignInWithServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,proto3" json:"client_id,omitempty"`
	ClientSecret  string                 `protobuf:"bytes,2,opt,name=client_secret,proto3" json:"client_secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignInWithServiceRequest) Reset() {
	*x = SignInWithServiceRequest{}
	mi := &file_internal_authenticator_authenticator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignInWithServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignInWithServiceRequest) ProtoMessage() {}

func (x *SignInWithServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_authenticator_authenticator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignInWithServiceRequest.ProtoReflect.Descriptor instead.
func (*SignInWithServiceRequest) Descriptor() ([]byte, []int) {
	return file_internal_authenticator_authenticator_proto_rawDescGZIP(), []int{0}
}

func (x *SignInWithServiceRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *SignInWithServiceRequest) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

type OAuthTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	TokenType     string                 `protobuf:"bytes,2,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`  // e.g., "Bearer"
	ExpiresIn     int64                  `protobuf:"varint,3,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"` // in seconds
	Scope         string                 `protobuf:"bytes,4,opt,name=scope,proto3" json:"scope,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,5,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"` // optional
	IssuedAt      int64                  `protobuf:"varint,6,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`            // Unix timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OAuthTokenResponse) Reset() {
	*x = OAuthTokenResponse{}
	mi := &file_internal_authenticator_authenticator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OAuthTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OAuthTokenResponse) ProtoMessage() {}

func (x *OAuthTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_authenticator_authenticator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OAuthTokenResponse.ProtoReflect.Descriptor instead.
func (*OAuthTokenResponse) Descriptor() ([]byte, []int) {
	return file_internal_authenticator_authenticator_proto_rawDescGZIP(), []int{1}
}

func (x *OAuthTokenResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *OAuthTokenResponse) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *OAuthTokenResponse) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

func (x *OAuthTokenResponse) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *OAuthTokenResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *OAuthTokenResponse) GetIssuedAt() int64 {
	if x != nil {
		return x.IssuedAt
	}
	return 0
}

type VerifyTokenRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: json:"token,optional"
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,optional"`
	// @gotags: json:"audiences,optional"
	Audiences []string `protobuf:"bytes,2,rep,name=audiences,proto3" json:"audiences,optional"`
	// @gotags: json:"enrich,optional"
	Enrich        bool `protobuf:"varint,3,opt,name=enrich,proto3" json:"enrich,optional"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyTokenRequest) Reset() {
	*x = VerifyTokenRequest{}
	mi := &file_internal_authenticator_authenticator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyTokenRequest) ProtoMessage() {}

func (x *VerifyTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_authenticator_authenticator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyTokenRequest.ProtoReflect.Descriptor instead.
func (*VerifyTokenRequest) Descriptor() ([]byte, []int) {
	return file_internal_authenticator_authenticator_proto_rawDescGZIP(), []int{2}
}

func (x *VerifyTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *VerifyTokenRequest) GetAudiences() []string {
	if x != nil {
		return x.Audiences
	}
	return nil
}

func (x *VerifyTokenRequest) GetEnrich() bool {
	if x != nil {
		return x.Enrich
	}
	return false
}

type VerifyTokenResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: json:"id"
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	// @gotags: json:"name"
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	// @gotags: json:"kind"
	Kind string `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind"`
	// @gotags: json:"source"
	Source string `protobuf:"bytes,4,opt,name=source,proto3" json:"source"`
	// @gotags: json:"roles,optional"
	Roles []string `protobuf:"bytes,5,rep,name=roles,proto3" json:"roles,optional"`
	// @gotags: json:"permissions,optional"
	Permissions []string `protobuf:"bytes,6,rep,name=permissions,proto3" json:"permissions,optional"`
	// @gotags: json:"expiry"
	Expiry int64 `protobuf:"varint,7,opt,name=expiry,proto3" json:"expiry"`
	// @gotags: json:"issuer"
	Issuer string `protobuf:"bytes,8,opt,name=issuer,proto3" json:"issuer"`
	// @gotags: json:"audience,optional"
	Audience []string `protobuf:"bytes,9,rep,name=audience,proto3" json:"audience,optional"`
	// @gotags: json:"attributes,optional"
	Attributes map[string]string `protobuf:"bytes,10,rep,name=attributes,proto3" json:"attributes,optional" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// @gotags: json:"single_session,optional"
	SingleSession bool `protobuf:"varint,11,opt,name=single_session,json=singleSession,proto3" json:"single_session,optional"`
	// @gotags: json:"jti,optional"
	Jti           string `protobuf:"bytes,12,opt,name=jti,proto3" json:"jti,optional"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyTokenResponse) Reset() {
	*x = VerifyTokenResponse{}
	mi := &file_internal_authenticator_authenticator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyTokenResponse) ProtoMessage() {}

func (x *VerifyTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_authenticator_authenticator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyTokenResponse.ProtoReflect.Descriptor instead.
func (*VerifyTokenResponse) Descriptor() ([]byte, []int) {
	return file_internal_authenticator_authenticator_proto_rawDescGZIP(), []int{3}
}

func (x *VerifyTokenResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VerifyTokenResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VerifyTokenResponse) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *VerifyTokenResponse) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *VerifyTokenResponse) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *VerifyTokenResponse) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *VerifyTokenResponse) GetExpiry() int64 {
	if x != nil {
		return x.Expiry
	}
	return 0
}

func (x *VerifyTokenResponse) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *VerifyTokenResponse) GetAudience() []string {
	if x != nil {
		return x.Audience
	}
	return nil
}

func (x *VerifyTokenResponse) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *VerifyTokenResponse) GetSingleSession() bool {
	if x != nil {
		return x.SingleSession
	}
	return false
}

func (x *VerifyTokenResponse) GetJti() string {
	if x != nil {
		return x.Jti
	}
	return ""
}

type RefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenRequest) Reset() {
	*x = RefreshTokenRequest{}
	mi := &file_internal_authenticator_authenticator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequest) ProtoMessage() {}

func (x *RefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_authenticator_authenticator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_internal_authenticator_authenticator_proto_rawDescGZIP(), []int{4}
}

func (x *RefreshTokenRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *RefreshTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type SignOutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Source        *string                `protobuf:"bytes,3,opt,name=source,proto3,oneof" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignOutRequest) Reset() {
	*x = SignOutRequest{}
	mi := &file_internal_authenticator_authenticator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignOutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignOutRequest) ProtoMessage() {}

func (x *SignOutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_authenticator_authenticator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignOutRequest.ProtoReflect.Descriptor instead.
func (*SignOutRequest) Descriptor() ([]byte, []int) {
	return file_internal_authenticator_authenticator_proto_rawDescGZIP(), []int{5}
}

func (x *SignOutRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *SignOutRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *SignOutRequest) GetSource() string {
	if x != nil && x.Source != nil {
		return *x.Source
	}
	return ""
}

var File_internal_authenticator_authenticator_proto protoreflect.FileDescriptor

const file_internal_authenticator_authenticator_proto_rawDesc = "" +
	"\n" +
	"*internal/authenticator/authenticator.proto\x12 pmc.inapp.internal.authenticator\x1a\x17validate/validate.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"u\n" +
	"\x18SignInWithServiceRequest\x12(\n" +
	"\tclient_id\x18\x01 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x01\x18\x80\x02R\tclient_id\x12/\n" +
	"\rclient_secret\x18\x02 \x01(\tB\t\xfaB\x06r\x04\x10\x04\x18 R\rclient_secret\"\xcd\x01\n" +
	"\x12OAuthTokenResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12\x1d\n" +
	"\n" +
	"token_type\x18\x02 \x01(\tR\ttokenType\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x03 \x01(\x03R\texpiresIn\x12\x14\n" +
	"\x05scope\x18\x04 \x01(\tR\x05scope\x12#\n" +
	"\rrefresh_token\x18\x05 \x01(\tR\frefreshToken\x12\x1b\n" +
	"\tissued_at\x18\x06 \x01(\x03R\bissuedAt\"`\n" +
	"\x12VerifyTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1c\n" +
	"\taudiences\x18\x02 \x03(\tR\taudiences\x12\x16\n" +
	"\x06enrich\x18\x03 \x01(\bR\x06enrich\"\xc8\x03\n" +
	"\x13VerifyTokenResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12\x14\n" +
	"\x05roles\x18\x05 \x03(\tR\x05roles\x12 \n" +
	"\vpermissions\x18\x06 \x03(\tR\vpermissions\x12\x16\n" +
	"\x06expiry\x18\a \x01(\x03R\x06expiry\x12\x16\n" +
	"\x06issuer\x18\b \x01(\tR\x06issuer\x12\x1a\n" +
	"\baudience\x18\t \x03(\tR\baudience\x12e\n" +
	"\n" +
	"attributes\x18\n" +
	" \x03(\v2E.pmc.inapp.internal.authenticator.VerifyTokenResponse.AttributesEntryR\n" +
	"attributes\x12%\n" +
	"\x0esingle_session\x18\v \x01(\bR\rsingleSession\x12\x10\n" +
	"\x03jti\x18\f \x01(\tR\x03jti\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"W\n" +
	"\x13RefreshTokenRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\"k\n" +
	"\x0eSignOutRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x1b\n" +
	"\x06source\x18\x03 \x01(\tH\x00R\x06source\x88\x01\x01B\t\n" +
	"\a_source2\xe5\x03\n" +
	"\rAuthenticator\x12\x85\x01\n" +
	"\x11SignInWithService\x12:.pmc.inapp.internal.authenticator.SignInWithServiceRequest\x1a4.pmc.inapp.internal.authenticator.OAuthTokenResponse\x12z\n" +
	"\vVerifyToken\x124.pmc.inapp.internal.authenticator.VerifyTokenRequest\x1a5.pmc.inapp.internal.authenticator.VerifyTokenResponse\x12{\n" +
	"\fRefreshToken\x125.pmc.inapp.internal.authenticator.RefreshTokenRequest\x1a4.pmc.inapp.internal.authenticator.OAuthTokenResponse\x12S\n" +
	"\aSignOut\x120.pmc.inapp.internal.authenticator.SignOutRequest\x1a\x16.google.protobuf.EmptyB\xe1\x02\x92A\x9d\x02\x12\xbc\x01\n" +
	"\x16Authentication Service\"=\n" +
	"\x18Pharmacity Internal Team\x12!https://github.com/Pharmacity-JSC*^\n" +
	"\x14BSD 3-Clause License\x12Fhttps://github.com/grpc-ecosystem/grpc-gateway/blob/master/LICENSE.txt2\x031.0*\x02\x02\x012\x10application/json:\x10application/jsonZ4\n" +
	"2\n" +
	"\rAuthorization\x12!\b\x02\x12\fBearer Token\x1a\rAuthorization \x02Z>pmc-inapp-authentication-svc/api/authenticator;authenticatorpbb\x06proto3"

var (
	file_internal_authenticator_authenticator_proto_rawDescOnce sync.Once
	file_internal_authenticator_authenticator_proto_rawDescData []byte
)

func file_internal_authenticator_authenticator_proto_rawDescGZIP() []byte {
	file_internal_authenticator_authenticator_proto_rawDescOnce.Do(func() {
		file_internal_authenticator_authenticator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_authenticator_authenticator_proto_rawDesc), len(file_internal_authenticator_authenticator_proto_rawDesc)))
	})
	return file_internal_authenticator_authenticator_proto_rawDescData
}

var file_internal_authenticator_authenticator_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_internal_authenticator_authenticator_proto_goTypes = []any{
	(*SignInWithServiceRequest)(nil), // 0: pmc.inapp.internal.authenticator.SignInWithServiceRequest
	(*OAuthTokenResponse)(nil),       // 1: pmc.inapp.internal.authenticator.OAuthTokenResponse
	(*VerifyTokenRequest)(nil),       // 2: pmc.inapp.internal.authenticator.VerifyTokenRequest
	(*VerifyTokenResponse)(nil),      // 3: pmc.inapp.internal.authenticator.VerifyTokenResponse
	(*RefreshTokenRequest)(nil),      // 4: pmc.inapp.internal.authenticator.RefreshTokenRequest
	(*SignOutRequest)(nil),           // 5: pmc.inapp.internal.authenticator.SignOutRequest
	nil,                              // 6: pmc.inapp.internal.authenticator.VerifyTokenResponse.AttributesEntry
	(*emptypb.Empty)(nil),            // 7: google.protobuf.Empty
}
var file_internal_authenticator_authenticator_proto_depIdxs = []int32{
	6, // 0: pmc.inapp.internal.authenticator.VerifyTokenResponse.attributes:type_name -> pmc.inapp.internal.authenticator.VerifyTokenResponse.AttributesEntry
	0, // 1: pmc.inapp.internal.authenticator.Authenticator.SignInWithService:input_type -> pmc.inapp.internal.authenticator.SignInWithServiceRequest
	2, // 2: pmc.inapp.internal.authenticator.Authenticator.VerifyToken:input_type -> pmc.inapp.internal.authenticator.VerifyTokenRequest
	4, // 3: pmc.inapp.internal.authenticator.Authenticator.RefreshToken:input_type -> pmc.inapp.internal.authenticator.RefreshTokenRequest
	5, // 4: pmc.inapp.internal.authenticator.Authenticator.SignOut:input_type -> pmc.inapp.internal.authenticator.SignOutRequest
	1, // 5: pmc.inapp.internal.authenticator.Authenticator.SignInWithService:output_type -> pmc.inapp.internal.authenticator.OAuthTokenResponse
	3, // 6: pmc.inapp.internal.authenticator.Authenticator.VerifyToken:output_type -> pmc.inapp.internal.authenticator.VerifyTokenResponse
	1, // 7: pmc.inapp.internal.authenticator.Authenticator.RefreshToken:output_type -> pmc.inapp.internal.authenticator.OAuthTokenResponse
	7, // 8: pmc.inapp.internal.authenticator.Authenticator.SignOut:output_type -> google.protobuf.Empty
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_authenticator_authenticator_proto_init() }
func file_internal_authenticator_authenticator_proto_init() {
	if File_internal_authenticator_authenticator_proto != nil {
		return
	}
	file_internal_authenticator_authenticator_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_authenticator_authenticator_proto_rawDesc), len(file_internal_authenticator_authenticator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_authenticator_authenticator_proto_goTypes,
		DependencyIndexes: file_internal_authenticator_authenticator_proto_depIdxs,
		MessageInfos:      file_internal_authenticator_authenticator_proto_msgTypes,
	}.Build()
	File_internal_authenticator_authenticator_proto = out.File
	file_internal_authenticator_authenticator_proto_goTypes = nil
	file_internal_authenticator_authenticator_proto_depIdxs = nil
}
