FROM timescale/timescaledb:latest-pg15

USER root
RUN apk add --no-cache --virtual .build-deps git make gcc musl-dev clang19 llvm19 \
    && ln -sf /usr/lib/llvm19/bin/clang /usr/bin/clang-19 \
    && cd /tmp \
    && git clone --branch v0.8.0 https://github.com/pgvector/pgvector.git \
    && cd pgvector \
    && make \
    && make install \
    && cd / && rm -rf /tmp/pgvector \
    && apk del .build-deps
USER postgres
