// Code generated by mockery v2.47.0. DO NOT EDIT.

package mocks

import (
	context "context"
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// Cache is an autogenerated mock type for the Cache type
type Cache struct {
	mock.Mock
}

// Del provides a mock function with given fields: keys
func (_m *Cache) Del(keys ...string) error {
	_va := make([]interface{}, len(keys))
	for _i := range keys {
		_va[_i] = keys[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Del")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(...string) error); ok {
		r0 = rf(keys...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DelByPatternCtx provides a mock function with given fields: ctx, pattern
func (_m *Cache) DelByPatternCtx(ctx context.Context, pattern string) error {
	ret := _m.Called(ctx, pattern)

	if len(ret) == 0 {
		panic("no return value specified for DelByPatternCtx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, pattern)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DelCtx provides a mock function with given fields: ctx, keys
func (_m *Cache) DelCtx(ctx context.Context, keys ...string) error {
	_va := make([]interface{}, len(keys))
	for _i := range keys {
		_va[_i] = keys[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DelCtx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, ...string) error); ok {
		r0 = rf(ctx, keys...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: key, val
func (_m *Cache) Get(key string, val any) error {
	ret := _m.Called(key, val)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, any) error); ok {
		r0 = rf(key, val)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetCtx provides a mock function with given fields: ctx, key, val
func (_m *Cache) GetCtx(ctx context.Context, key string, val any) error {
	ret := _m.Called(ctx, key, val)

	if len(ret) == 0 {
		panic("no return value specified for GetCtx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, any) error); ok {
		r0 = rf(ctx, key, val)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IsNotFound provides a mock function with given fields: err
func (_m *Cache) IsNotFound(err error) bool {
	ret := _m.Called(err)

	if len(ret) == 0 {
		panic("no return value specified for IsNotFound")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(error) bool); ok {
		r0 = rf(err)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Set provides a mock function with given fields: key, val
func (_m *Cache) Set(key string, val any) error {
	ret := _m.Called(key, val)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, any) error); ok {
		r0 = rf(key, val)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetCtx provides a mock function with given fields: ctx, key, val
func (_m *Cache) SetCtx(ctx context.Context, key string, val any) error {
	ret := _m.Called(ctx, key, val)

	if len(ret) == 0 {
		panic("no return value specified for SetCtx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, any) error); ok {
		r0 = rf(ctx, key, val)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetWithExpire provides a mock function with given fields: key, val, expire
func (_m *Cache) SetWithExpire(key string, val any, expire time.Duration) error {
	ret := _m.Called(key, val, expire)

	if len(ret) == 0 {
		panic("no return value specified for SetWithExpire")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, any, time.Duration) error); ok {
		r0 = rf(key, val, expire)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetWithExpireCtx provides a mock function with given fields: ctx, key, val, expire
func (_m *Cache) SetWithExpireCtx(ctx context.Context, key string, val any, expire time.Duration) error {
	ret := _m.Called(ctx, key, val, expire)

	if len(ret) == 0 {
		panic("no return value specified for SetWithExpireCtx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, any, time.Duration) error); ok {
		r0 = rf(ctx, key, val, expire)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Take provides a mock function with given fields: val, key, query
func (_m *Cache) Take(val any, key string, query func(any) error) error {
	ret := _m.Called(val, key, query)

	if len(ret) == 0 {
		panic("no return value specified for Take")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(any, string, func(any) error) error); ok {
		r0 = rf(val, key, query)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TakeCtx provides a mock function with given fields: ctx, val, key, query
func (_m *Cache) TakeCtx(ctx context.Context, val any, key string, query func(any) error) error {
	ret := _m.Called(ctx, val, key, query)

	if len(ret) == 0 {
		panic("no return value specified for TakeCtx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, any, string, func(any) error) error); ok {
		r0 = rf(ctx, val, key, query)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TakeWithExpire provides a mock function with given fields: val, key, query
func (_m *Cache) TakeWithExpire(val any, key string, query func(any, time.Duration) error) error {
	ret := _m.Called(val, key, query)

	if len(ret) == 0 {
		panic("no return value specified for TakeWithExpire")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(any, string, func(any, time.Duration) error) error); ok {
		r0 = rf(val, key, query)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TakeWithExpireCtx provides a mock function with given fields: ctx, val, key, query
func (_m *Cache) TakeWithExpireCtx(ctx context.Context, val any, key string, query func(any, time.Duration) error) error {
	ret := _m.Called(ctx, val, key, query)

	if len(ret) == 0 {
		panic("no return value specified for TakeWithExpireCtx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, any, string, func(any, time.Duration) error) error); ok {
		r0 = rf(ctx, val, key, query)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCache creates a new instance of Cache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *Cache {
	mock := &Cache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
