global:
  scrape_interval: 15s

scrape_configs:
  - job_name: pulse-api
    static_configs:
      - targets: ['api:8000']
    metrics_path: /v1/metrics

  - job_name: pulse-ingest
    static_configs:
      - targets: ['ingest:8002']
    metrics_path: /v1/metrics

  - job_name: pulse-worker
    static_configs:
      - targets: ['worker:9090']
    metrics_path: /metrics

  - job_name: redpanda
    static_configs:
      - targets: ['kafka:9644']
    metrics_path: /metrics
