// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.26.1
// source: api/search/search.proto

package searchpb

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	common "pulse/api/common"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LogEntry is the read model for a log_entries row served to API consumers.
type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ServiceName   string                 `protobuf:"bytes,2,opt,name=service_name,proto3" json:"service_name,omitempty"`
	Level         string                 `protobuf:"bytes,3,opt,name=level,proto3" json:"level,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Fingerprint   string                 `protobuf:"bytes,5,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_api_search_search_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_api_search_search_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_api_search_search_proto_rawDescGZIP(), []int{0}
}

func (x *LogEntry) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LogEntry) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *LogEntry) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogEntry) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *LogEntry) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *LogEntry) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type SearchLogsRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	ServiceName string                 `protobuf:"bytes,1,opt,name=service_name,proto3" json:"service_name,omitempty"`
	Level       string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	Fingerprint string                 `protobuf:"bytes,3,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	// query is a full-text search string matched against message.
	Query         string                 `protobuf:"bytes,4,opt,name=query,proto3" json:"query,omitempty"`
	From          *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=from,proto3" json:"from,omitempty"`
	To            *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=to,proto3" json:"to,omitempty"`
	Page          int32                  `protobuf:"varint,7,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,8,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchLogsRequest) Reset() {
	*x = SearchLogsRequest{}
	mi := &file_api_search_search_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchLogsRequest) ProtoMessage() {}

func (x *SearchLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_search_search_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchLogsRequest.ProtoReflect.Descriptor instead.
func (*SearchLogsRequest) Descriptor() ([]byte, []int) {
	return file_api_search_search_proto_rawDescGZIP(), []int{1}
}

func (x *SearchLogsRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *SearchLogsRequest) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *SearchLogsRequest) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *SearchLogsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchLogsRequest) GetFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *SearchLogsRequest) GetTo() *timestamppb.Timestamp {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *SearchLogsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchLogsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SearchLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*LogEntry            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Pagination    *common.Pagination     `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchLogsResponse) Reset() {
	*x = SearchLogsResponse{}
	mi := &file_api_search_search_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchLogsResponse) ProtoMessage() {}

func (x *SearchLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_search_search_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchLogsResponse.ProtoReflect.Descriptor instead.
func (*SearchLogsResponse) Descriptor() ([]byte, []int) {
	return file_api_search_search_proto_rawDescGZIP(), []int{2}
}

func (x *SearchLogsResponse) GetItems() []*LogEntry {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *SearchLogsResponse) GetPagination() *common.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type GetLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLogRequest) Reset() {
	*x = GetLogRequest{}
	mi := &file_api_search_search_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLogRequest) ProtoMessage() {}

func (x *GetLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_search_search_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLogRequest.ProtoReflect.Descriptor instead.
func (*GetLogRequest) Descriptor() ([]byte, []int) {
	return file_api_search_search_proto_rawDescGZIP(), []int{3}
}

func (x *GetLogRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetLogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Log           *LogEntry              `protobuf:"bytes,1,opt,name=log,proto3" json:"log,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLogResponse) Reset() {
	*x = GetLogResponse{}
	mi := &file_api_search_search_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLogResponse) ProtoMessage() {}

func (x *GetLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_search_search_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLogResponse.ProtoReflect.Descriptor instead.
func (*GetLogResponse) Descriptor() ([]byte, []int) {
	return file_api_search_search_proto_rawDescGZIP(), []int{4}
}

func (x *GetLogResponse) GetLog() *LogEntry {
	if x != nil {
		return x.Log
	}
	return nil
}

var File_api_search_search_proto protoreflect.FileDescriptor

const file_api_search_search_proto_rawDesc = "" +
	"\n" +
	"\x17api/search/search.proto\x12\fpulse.search\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x17validate/validate.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x17api/common/common.proto\"\x81\x02\n" +
	"\bLogEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\"\n" +
	"\fservice_name\x18\x02 \x01(\tR\fservice_name\x12\x14\n" +
	"\x05level\x18\x03 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12 \n" +
	"\vfingerprint\x18\x05 \x01(\tR\vfingerprint\x123\n" +
	"\bmetadata\x18\x06 \x01(\v2\x17.google.protobuf.StructR\bmetadata\x12:\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"created_at\"\x8b\x02\n" +
	"\x11SearchLogsRequest\x12\"\n" +
	"\fservice_name\x18\x01 \x01(\tR\fservice_name\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12 \n" +
	"\vfingerprint\x18\x03 \x01(\tR\vfingerprint\x12\x14\n" +
	"\x05query\x18\x04 \x01(\tR\x05query\x12.\n" +
	"\x04from\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x04from\x12*\n" +
	"\x02to\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x02to\x12\x12\n" +
	"\x04page\x18\a \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\b \x01(\x05R\x05limit\"|\n" +
	"\x12SearchLogsResponse\x12,\n" +
	"\x05items\x18\x01 \x03(\v2\x16.pulse.search.LogEntryR\x05items\x128\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x18.pulse.common.PaginationR\n" +
	"pagination\"(\n" +
	"\rGetLogRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x02id\":\n" +
	"\x0eGetLogResponse\x12(\n" +
	"\x03log\x18\x01 \x01(\v2\x16.pulse.search.LogEntryR\x03log2\x98\x02\n" +
	"\rSearchService\x12\x80\x01\n" +
	"\n" +
	"SearchLogs\x12\x1f.pulse.search.SearchLogsRequest\x1a .pulse.search.SearchLogsResponse\"/\x92A\x1c\n" +
	"\x06Search\x12\x12Search log entries\x82\xd3\xe4\x93\x02\n" +
	"\x12\b/v1/logs\x12\x83\x01\n" +
	"\x06GetLog\x12\x1b.pulse.search.GetLogRequest\x1a\x1c.pulse.search.GetLogResponse\">\x92A&\n" +
	"\x06Search\x12\x1cGet a single log entry by ID\x82\xd3\xe4\x93\x02\x0f\x12\r/v1/logs/{id}B\x96\x01\x92Ax\x12\x17\n" +
	"\x10Pulse Search API2\x031.0*\x02\x01\x022\x10application/json:\x10application/jsonZ5\n" +
	"3\n" +
	"\n" +
	"BearerAuth\x12%\b\x02\x12\x10Bearer JWT token\x1a\rAuthorization \x02Z\x19pulse/api/search;searchpbb\x06proto3"

var (
	file_api_search_search_proto_rawDescOnce sync.Once
	file_api_search_search_proto_rawDescData []byte
)

func file_api_search_search_proto_rawDescGZIP() []byte {
	file_api_search_search_proto_rawDescOnce.Do(func() {
		file_api_search_search_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_search_search_proto_rawDesc), len(file_api_search_search_proto_rawDesc)))
	})
	return file_api_search_search_proto_rawDescData
}

var file_api_search_search_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_search_search_proto_goTypes = []any{
	(*LogEntry)(nil),              // 0: pulse.search.LogEntry
	(*SearchLogsRequest)(nil),     // 1: pulse.search.SearchLogsRequest
	(*SearchLogsResponse)(nil),    // 2: pulse.search.SearchLogsResponse
	(*GetLogRequest)(nil),         // 3: pulse.search.GetLogRequest
	(*GetLogResponse)(nil),        // 4: pulse.search.GetLogResponse
	(*structpb.Struct)(nil),       // 5: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
	(*common.Pagination)(nil),     // 7: pulse.common.Pagination
}
var file_api_search_search_proto_depIdxs = []int32{
	5, // 0: pulse.search.LogEntry.metadata:type_name -> google.protobuf.Struct
	6, // 1: pulse.search.LogEntry.created_at:type_name -> google.protobuf.Timestamp
	6, // 2: pulse.search.SearchLogsRequest.from:type_name -> google.protobuf.Timestamp
	6, // 3: pulse.search.SearchLogsRequest.to:type_name -> google.protobuf.Timestamp
	0, // 4: pulse.search.SearchLogsResponse.items:type_name -> pulse.search.LogEntry
	7, // 5: pulse.search.SearchLogsResponse.pagination:type_name -> pulse.common.Pagination
	0, // 6: pulse.search.GetLogResponse.log:type_name -> pulse.search.LogEntry
	1, // 7: pulse.search.SearchService.SearchLogs:input_type -> pulse.search.SearchLogsRequest
	3, // 8: pulse.search.SearchService.GetLog:input_type -> pulse.search.GetLogRequest
	2, // 9: pulse.search.SearchService.SearchLogs:output_type -> pulse.search.SearchLogsResponse
	4, // 10: pulse.search.SearchService.GetLog:output_type -> pulse.search.GetLogResponse
	9, // [9:11] is the sub-list for method output_type
	7, // [7:9] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_api_search_search_proto_init() }
func file_api_search_search_proto_init() {
	if File_api_search_search_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_search_search_proto_rawDesc), len(file_api_search_search_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_search_search_proto_goTypes,
		DependencyIndexes: file_api_search_search_proto_depIdxs,
		MessageInfos:      file_api_search_search_proto_msgTypes,
	}.Build()
	File_api_search_search_proto = out.File
	file_api_search_search_proto_goTypes = nil
	file_api_search_search_proto_depIdxs = nil
}
