// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: pmcpb/protobuf/common.proto

package pmcpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Pagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	TotalPage     int32                  `protobuf:"varint,4,opt,name=total_page,proto3" json:"total_page,omitempty"`
	TotalRecords  int64                  `protobuf:"varint,3,opt,name=total_records,proto3" json:"total_records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	mi := &file_pmcpb_protobuf_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_pmcpb_protobuf_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_pmcpb_protobuf_common_proto_rawDescGZIP(), []int{0}
}

func (x *Pagination) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *Pagination) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *Pagination) GetTotalPage() int32 {
	if x != nil {
		return x.TotalPage
	}
	return 0
}

func (x *Pagination) GetTotalRecords() int64 {
	if x != nil {
		return x.TotalRecords
	}
	return 0
}

type AuditMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: json:"created_by"
	CreatedBy string `protobuf:"bytes,1,opt,name=created_by,proto3" json:"created_by,omitempty"`
	// @gotags: json:"created_by_uid"
	CreatedByUid string `protobuf:"bytes,2,opt,name=created_by_uid,proto3" json:"created_by_uid,omitempty"`
	// @gotags: json:"updated_by"
	UpdatedBy string `protobuf:"bytes,3,opt,name=updated_by,proto3" json:"updated_by,omitempty"`
	// @gotags: json:"updated_by_uid"
	UpdatedByUid string `protobuf:"bytes,4,opt,name=updated_by_uid,proto3" json:"updated_by_uid,omitempty"`
	// @gotags: json:"created_at"
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,proto3" json:"created_at,omitempty"`
	// @gotags: json:"updated_at"
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditMetadata) Reset() {
	*x = AuditMetadata{}
	mi := &file_pmcpb_protobuf_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditMetadata) ProtoMessage() {}

func (x *AuditMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_pmcpb_protobuf_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditMetadata.ProtoReflect.Descriptor instead.
func (*AuditMetadata) Descriptor() ([]byte, []int) {
	return file_pmcpb_protobuf_common_proto_rawDescGZIP(), []int{1}
}

func (x *AuditMetadata) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *AuditMetadata) GetCreatedByUid() string {
	if x != nil {
		return x.CreatedByUid
	}
	return ""
}

func (x *AuditMetadata) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

func (x *AuditMetadata) GetUpdatedByUid() string {
	if x != nil {
		return x.UpdatedByUid
	}
	return ""
}

func (x *AuditMetadata) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *AuditMetadata) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ListOptionsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: json:"options"
	Options       []*ListOptionsResponse_Option `protobuf:"bytes,1,rep,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOptionsResponse) Reset() {
	*x = ListOptionsResponse{}
	mi := &file_pmcpb_protobuf_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOptionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOptionsResponse) ProtoMessage() {}

func (x *ListOptionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pmcpb_protobuf_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOptionsResponse.ProtoReflect.Descriptor instead.
func (*ListOptionsResponse) Descriptor() ([]byte, []int) {
	return file_pmcpb_protobuf_common_proto_rawDescGZIP(), []int{2}
}

func (x *ListOptionsResponse) GetOptions() []*ListOptionsResponse_Option {
	if x != nil {
		return x.Options
	}
	return nil
}

type FileInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=file_name,proto3" json:"file_name,omitempty"`
	FileData      []byte                 `protobuf:"bytes,2,opt,name=file_data,proto3" json:"file_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	mi := &file_pmcpb_protobuf_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pmcpb_protobuf_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_pmcpb_protobuf_common_proto_rawDescGZIP(), []int{3}
}

func (x *FileInfo) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *FileInfo) GetFileData() []byte {
	if x != nil {
		return x.FileData
	}
	return nil
}

type ExportResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*ExportResponse_FileData
	//	*ExportResponse_ErrorMessage
	Result isExportResponse_Result `protobuf_oneof:"result"`
	// @gotags: json:"file_name"
	FileName      string `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportResponse) Reset() {
	*x = ExportResponse{}
	mi := &file_pmcpb_protobuf_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportResponse) ProtoMessage() {}

func (x *ExportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pmcpb_protobuf_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportResponse.ProtoReflect.Descriptor instead.
func (*ExportResponse) Descriptor() ([]byte, []int) {
	return file_pmcpb_protobuf_common_proto_rawDescGZIP(), []int{4}
}

func (x *ExportResponse) GetResult() isExportResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ExportResponse) GetFileData() []byte {
	if x != nil {
		if x, ok := x.Result.(*ExportResponse_FileData); ok {
			return x.FileData
		}
	}
	return nil
}

func (x *ExportResponse) GetErrorMessage() string {
	if x != nil {
		if x, ok := x.Result.(*ExportResponse_ErrorMessage); ok {
			return x.ErrorMessage
		}
	}
	return ""
}

func (x *ExportResponse) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type isExportResponse_Result interface {
	isExportResponse_Result()
}

type ExportResponse_FileData struct {
	FileData []byte `protobuf:"bytes,1,opt,name=file_data,json=fileData,proto3,oneof"`
}

type ExportResponse_ErrorMessage struct {
	ErrorMessage string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3,oneof"`
}

func (*ExportResponse_FileData) isExportResponse_Result() {}

func (*ExportResponse_ErrorMessage) isExportResponse_Result() {}

type ListOptionsResponse_Option struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: json:"uid"
	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	// @gotags: json:"name"
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOptionsResponse_Option) Reset() {
	*x = ListOptionsResponse_Option{}
	mi := &file_pmcpb_protobuf_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOptionsResponse_Option) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOptionsResponse_Option) ProtoMessage() {}

func (x *ListOptionsResponse_Option) ProtoReflect() protoreflect.Message {
	mi := &file_pmcpb_protobuf_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOptionsResponse_Option.ProtoReflect.Descriptor instead.
func (*ListOptionsResponse_Option) Descriptor() ([]byte, []int) {
	return file_pmcpb_protobuf_common_proto_rawDescGZIP(), []int{2, 0}
}

func (x *ListOptionsResponse_Option) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *ListOptionsResponse_Option) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var file_pmcpb_protobuf_common_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         1000,
		Name:          "pmcpb.protobuf.permission_code",
		Tag:           "bytes,1000,opt,name=permission_code",
		Filename:      "pmcpb/protobuf/common.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional string permission_code = 1000;
	E_PermissionCode = &file_pmcpb_protobuf_common_proto_extTypes[0]
)

var File_pmcpb_protobuf_common_proto protoreflect.FileDescriptor

const file_pmcpb_protobuf_common_proto_rawDesc = "" +
	"\n" +
	"\x1bpmcpb/protobuf/common.proto\x12\x0epmcpb.protobuf\x1a\x1fgoogle/protobuf/timestamp.proto\x1a google/protobuf/descriptor.proto\"|\n" +
	"\n" +
	"Pagination\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1e\n" +
	"\n" +
	"total_page\x18\x04 \x01(\x05R\n" +
	"total_page\x12$\n" +
	"\rtotal_records\x18\x03 \x01(\x03R\rtotal_records\"\x97\x02\n" +
	"\rAuditMetadata\x12\x1e\n" +
	"\n" +
	"created_by\x18\x01 \x01(\tR\n" +
	"created_by\x12&\n" +
	"\x0ecreated_by_uid\x18\x02 \x01(\tR\x0ecreated_by_uid\x12\x1e\n" +
	"\n" +
	"updated_by\x18\x03 \x01(\tR\n" +
	"updated_by\x12&\n" +
	"\x0eupdated_by_uid\x18\x04 \x01(\tR\x0eupdated_by_uid\x12:\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"created_at\x12:\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updated_at\"\x8b\x01\n" +
	"\x13ListOptionsResponse\x12D\n" +
	"\aoptions\x18\x01 \x03(\v2*.pmcpb.protobuf.ListOptionsResponse.OptionR\aoptions\x1a.\n" +
	"\x06Option\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"F\n" +
	"\bFileInfo\x12\x1c\n" +
	"\tfile_name\x18\x01 \x01(\tR\tfile_name\x12\x1c\n" +
	"\tfile_data\x18\x02 \x01(\fR\tfile_data\"}\n" +
	"\x0eExportResponse\x12\x1d\n" +
	"\tfile_data\x18\x01 \x01(\fH\x00R\bfileData\x12%\n" +
	"\rerror_message\x18\x02 \x01(\tH\x00R\ferrorMessage\x12\x1b\n" +
	"\tfile_name\x18\x03 \x01(\tR\bfileNameB\b\n" +
	"\x06result:H\n" +
	"\x0fpermission_code\x12\x1e.google.protobuf.MethodOptions\x18\xe8\a \x01(\tR\x0epermissionCodeBaZ_dev.azure.com/PHARMACITYJSC/PharmacityLibrary/_git/pmc-inapp-helper.git/v2/pmcpb/protobuf;pmcpbb\x06proto3"

var (
	file_pmcpb_protobuf_common_proto_rawDescOnce sync.Once
	file_pmcpb_protobuf_common_proto_rawDescData []byte
)

func file_pmcpb_protobuf_common_proto_rawDescGZIP() []byte {
	file_pmcpb_protobuf_common_proto_rawDescOnce.Do(func() {
		file_pmcpb_protobuf_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pmcpb_protobuf_common_proto_rawDesc), len(file_pmcpb_protobuf_common_proto_rawDesc)))
	})
	return file_pmcpb_protobuf_common_proto_rawDescData
}

var file_pmcpb_protobuf_common_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pmcpb_protobuf_common_proto_goTypes = []any{
	(*Pagination)(nil),                 // 0: pmcpb.protobuf.Pagination
	(*AuditMetadata)(nil),              // 1: pmcpb.protobuf.AuditMetadata
	(*ListOptionsResponse)(nil),        // 2: pmcpb.protobuf.ListOptionsResponse
	(*FileInfo)(nil),                   // 3: pmcpb.protobuf.FileInfo
	(*ExportResponse)(nil),             // 4: pmcpb.protobuf.ExportResponse
	(*ListOptionsResponse_Option)(nil), // 5: pmcpb.protobuf.ListOptionsResponse.Option
	(*timestamppb.Timestamp)(nil),      // 6: google.protobuf.Timestamp
	(*descriptorpb.MethodOptions)(nil), // 7: google.protobuf.MethodOptions
}
var file_pmcpb_protobuf_common_proto_depIdxs = []int32{
	6, // 0: pmcpb.protobuf.AuditMetadata.created_at:type_name -> google.protobuf.Timestamp
	6, // 1: pmcpb.protobuf.AuditMetadata.updated_at:type_name -> google.protobuf.Timestamp
	5, // 2: pmcpb.protobuf.ListOptionsResponse.options:type_name -> pmcpb.protobuf.ListOptionsResponse.Option
	7, // 3: pmcpb.protobuf.permission_code:extendee -> google.protobuf.MethodOptions
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	3, // [3:4] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pmcpb_protobuf_common_proto_init() }
func file_pmcpb_protobuf_common_proto_init() {
	if File_pmcpb_protobuf_common_proto != nil {
		return
	}
	file_pmcpb_protobuf_common_proto_msgTypes[4].OneofWrappers = []any{
		(*ExportResponse_FileData)(nil),
		(*ExportResponse_ErrorMessage)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pmcpb_protobuf_common_proto_rawDesc), len(file_pmcpb_protobuf_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_pmcpb_protobuf_common_proto_goTypes,
		DependencyIndexes: file_pmcpb_protobuf_common_proto_depIdxs,
		MessageInfos:      file_pmcpb_protobuf_common_proto_msgTypes,
		ExtensionInfos:    file_pmcpb_protobuf_common_proto_extTypes,
	}.Build()
	File_pmcpb_protobuf_common_proto = out.File
	file_pmcpb_protobuf_common_proto_goTypes = nil
	file_pmcpb_protobuf_common_proto_depIdxs = nil
}
