// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: internal/permission/subject.proto

package permissionpb

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAccessRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ExternalId         string                 `protobuf:"bytes,1,opt,name=external_id,proto3" json:"external_id,omitempty"`
	IncludeRoles       bool                   `protobuf:"varint,2,opt,name=include_roles,proto3" json:"include_roles,omitempty"`
	IncludeGroups      bool                   `protobuf:"varint,3,opt,name=include_groups,proto3" json:"include_groups,omitempty"`
	IncludePermissions bool                   `protobuf:"varint,4,opt,name=include_permissions,proto3" json:"include_permissions,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetAccessRequest) Reset() {
	*x = GetAccessRequest{}
	mi := &file_internal_permission_subject_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccessRequest) ProtoMessage() {}

func (x *GetAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_permission_subject_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccessRequest.ProtoReflect.Descriptor instead.
func (*GetAccessRequest) Descriptor() ([]byte, []int) {
	return file_internal_permission_subject_proto_rawDescGZIP(), []int{0}
}

func (x *GetAccessRequest) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *GetAccessRequest) GetIncludeRoles() bool {
	if x != nil {
		return x.IncludeRoles
	}
	return false
}

func (x *GetAccessRequest) GetIncludeGroups() bool {
	if x != nil {
		return x.IncludeGroups
	}
	return false
}

func (x *GetAccessRequest) GetIncludePermissions() bool {
	if x != nil {
		return x.IncludePermissions
	}
	return false
}

type GetAccessCodesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: json:"permissions"
	Permissions []string `protobuf:"bytes,1,rep,name=permissions,proto3" json:"permissions"`
	// @gotags: json:"roles"
	Roles         []string `protobuf:"bytes,2,rep,name=roles,proto3" json:"roles"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccessCodesResponse) Reset() {
	*x = GetAccessCodesResponse{}
	mi := &file_internal_permission_subject_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccessCodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccessCodesResponse) ProtoMessage() {}

func (x *GetAccessCodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_permission_subject_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccessCodesResponse.ProtoReflect.Descriptor instead.
func (*GetAccessCodesResponse) Descriptor() ([]byte, []int) {
	return file_internal_permission_subject_proto_rawDescGZIP(), []int{1}
}

func (x *GetAccessCodesResponse) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *GetAccessCodesResponse) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

type GetAccessIdsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: json:"groups"
	Groups []*GetAccessIdsResponse_Access `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups"`
	// @gotags: json:"roles"
	Roles []*GetAccessIdsResponse_Access `protobuf:"bytes,2,rep,name=roles,proto3" json:"roles"`
	// @gotags: json:"permissions"
	Permissions   []*GetAccessIdsResponse_Access `protobuf:"bytes,3,rep,name=permissions,proto3" json:"permissions"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccessIdsResponse) Reset() {
	*x = GetAccessIdsResponse{}
	mi := &file_internal_permission_subject_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccessIdsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccessIdsResponse) ProtoMessage() {}

func (x *GetAccessIdsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_permission_subject_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccessIdsResponse.ProtoReflect.Descriptor instead.
func (*GetAccessIdsResponse) Descriptor() ([]byte, []int) {
	return file_internal_permission_subject_proto_rawDescGZIP(), []int{2}
}

func (x *GetAccessIdsResponse) GetGroups() []*GetAccessIdsResponse_Access {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *GetAccessIdsResponse) GetRoles() []*GetAccessIdsResponse_Access {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *GetAccessIdsResponse) GetPermissions() []*GetAccessIdsResponse_Access {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type GetInternalRoleCodesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExternalId    string                 `protobuf:"bytes,1,opt,name=external_id,proto3" json:"external_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInternalRoleCodesRequest) Reset() {
	*x = GetInternalRoleCodesRequest{}
	mi := &file_internal_permission_subject_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInternalRoleCodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInternalRoleCodesRequest) ProtoMessage() {}

func (x *GetInternalRoleCodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_permission_subject_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInternalRoleCodesRequest.ProtoReflect.Descriptor instead.
func (*GetInternalRoleCodesRequest) Descriptor() ([]byte, []int) {
	return file_internal_permission_subject_proto_rawDescGZIP(), []int{3}
}

func (x *GetInternalRoleCodesRequest) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

type GetAccessIdsResponse_Access struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccessIdsResponse_Access) Reset() {
	*x = GetAccessIdsResponse_Access{}
	mi := &file_internal_permission_subject_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccessIdsResponse_Access) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccessIdsResponse_Access) ProtoMessage() {}

func (x *GetAccessIdsResponse_Access) ProtoReflect() protoreflect.Message {
	mi := &file_internal_permission_subject_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccessIdsResponse_Access.ProtoReflect.Descriptor instead.
func (*GetAccessIdsResponse_Access) Descriptor() ([]byte, []int) {
	return file_internal_permission_subject_proto_rawDescGZIP(), []int{2, 0}
}

func (x *GetAccessIdsResponse_Access) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetAccessIdsResponse_Access) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_internal_permission_subject_proto protoreflect.FileDescriptor

const file_internal_permission_subject_proto_rawDesc = "" +
	"\n" +
	"!internal/permission/subject.proto\x12\x1dpmc.inapp.internal.permission\x1a\x17validate/validate.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xbf\x01\n" +
	"\x10GetAccessRequest\x12+\n" +
	"\vexternal_id\x18\x01 \x01(\tB\t\xfaB\x06r\x04\x10\x04\x182R\vexternal_id\x12$\n" +
	"\rinclude_roles\x18\x02 \x01(\bR\rinclude_roles\x12&\n" +
	"\x0einclude_groups\x18\x03 \x01(\bR\x0einclude_groups\x120\n" +
	"\x13include_permissions\x18\x04 \x01(\bR\x13include_permissions\"P\n" +
	"\x16GetAccessCodesResponse\x12 \n" +
	"\vpermissions\x18\x01 \x03(\tR\vpermissions\x12\x14\n" +
	"\x05roles\x18\x02 \x03(\tR\x05roles\"\xc8\x02\n" +
	"\x14GetAccessIdsResponse\x12R\n" +
	"\x06groups\x18\x01 \x03(\v2:.pmc.inapp.internal.permission.GetAccessIdsResponse.AccessR\x06groups\x12P\n" +
	"\x05roles\x18\x02 \x03(\v2:.pmc.inapp.internal.permission.GetAccessIdsResponse.AccessR\x05roles\x12\\\n" +
	"\vpermissions\x18\x03 \x03(\v2:.pmc.inapp.internal.permission.GetAccessIdsResponse.AccessR\vpermissions\x1a,\n" +
	"\x06Access\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"J\n" +
	"\x1bGetInternalRoleCodesRequest\x12+\n" +
	"\vexternal_id\x18\x01 \x01(\tB\t\xfaB\x06r\x04\x10\x04\x182R\vexternal_id2\x85\x03\n" +
	"\aSubject\x12x\n" +
	"\x0eGetAccessCodes\x12/.pmc.inapp.internal.permission.GetAccessRequest\x1a5.pmc.inapp.internal.permission.GetAccessCodesResponse\x12t\n" +
	"\fGetAccessIds\x12/.pmc.inapp.internal.permission.GetAccessRequest\x1a3.pmc.inapp.internal.permission.GetAccessIdsResponse\x12\x89\x01\n" +
	"\x14GetInternalRoleCodes\x12:.pmc.inapp.internal.permission.GetInternalRoleCodesRequest\x1a5.pmc.inapp.internal.permission.GetAccessCodesResponseB\xec\x02\x92A\xb2\x02\x12\xbc\x01\n" +
	"\x16Authentication Service\"=\n" +
	"\x18Pharmacity Internal Team\x12!https://github.com/Pharmacity-JSC*^\n" +
	"\x14BSD 3-Clause License\x12Fhttps://github.com/grpc-ecosystem/grpc-gateway/blob/master/LICENSE.txt2\x031.0*\x02\x02\x012\x10application/json:\x10application/jsonZ4\n" +
	"2\n" +
	"\rAuthorization\x12!\b\x02\x12\fBearer Token\x1a\rAuthorization \x02b\x13\n" +
	"\x11\n" +
	"\rAuthorization\x12\x00Z4pmc-inapp-permission-svc/api/permission;permissionpbb\x06proto3"

var (
	file_internal_permission_subject_proto_rawDescOnce sync.Once
	file_internal_permission_subject_proto_rawDescData []byte
)

func file_internal_permission_subject_proto_rawDescGZIP() []byte {
	file_internal_permission_subject_proto_rawDescOnce.Do(func() {
		file_internal_permission_subject_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_permission_subject_proto_rawDesc), len(file_internal_permission_subject_proto_rawDesc)))
	})
	return file_internal_permission_subject_proto_rawDescData
}

var file_internal_permission_subject_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_internal_permission_subject_proto_goTypes = []any{
	(*GetAccessRequest)(nil),            // 0: pmc.inapp.internal.permission.GetAccessRequest
	(*GetAccessCodesResponse)(nil),      // 1: pmc.inapp.internal.permission.GetAccessCodesResponse
	(*GetAccessIdsResponse)(nil),        // 2: pmc.inapp.internal.permission.GetAccessIdsResponse
	(*GetInternalRoleCodesRequest)(nil), // 3: pmc.inapp.internal.permission.GetInternalRoleCodesRequest
	(*GetAccessIdsResponse_Access)(nil), // 4: pmc.inapp.internal.permission.GetAccessIdsResponse.Access
}
var file_internal_permission_subject_proto_depIdxs = []int32{
	4, // 0: pmc.inapp.internal.permission.GetAccessIdsResponse.groups:type_name -> pmc.inapp.internal.permission.GetAccessIdsResponse.Access
	4, // 1: pmc.inapp.internal.permission.GetAccessIdsResponse.roles:type_name -> pmc.inapp.internal.permission.GetAccessIdsResponse.Access
	4, // 2: pmc.inapp.internal.permission.GetAccessIdsResponse.permissions:type_name -> pmc.inapp.internal.permission.GetAccessIdsResponse.Access
	0, // 3: pmc.inapp.internal.permission.Subject.GetAccessCodes:input_type -> pmc.inapp.internal.permission.GetAccessRequest
	0, // 4: pmc.inapp.internal.permission.Subject.GetAccessIds:input_type -> pmc.inapp.internal.permission.GetAccessRequest
	3, // 5: pmc.inapp.internal.permission.Subject.GetInternalRoleCodes:input_type -> pmc.inapp.internal.permission.GetInternalRoleCodesRequest
	1, // 6: pmc.inapp.internal.permission.Subject.GetAccessCodes:output_type -> pmc.inapp.internal.permission.GetAccessCodesResponse
	2, // 7: pmc.inapp.internal.permission.Subject.GetAccessIds:output_type -> pmc.inapp.internal.permission.GetAccessIdsResponse
	1, // 8: pmc.inapp.internal.permission.Subject.GetInternalRoleCodes:output_type -> pmc.inapp.internal.permission.GetAccessCodesResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_internal_permission_subject_proto_init() }
func file_internal_permission_subject_proto_init() {
	if File_internal_permission_subject_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_permission_subject_proto_rawDesc), len(file_internal_permission_subject_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_permission_subject_proto_goTypes,
		DependencyIndexes: file_internal_permission_subject_proto_depIdxs,
		MessageInfos:      file_internal_permission_subject_proto_msgTypes,
	}.Build()
	File_internal_permission_subject_proto = out.File
	file_internal_permission_subject_proto_goTypes = nil
	file_internal_permission_subject_proto_depIdxs = nil
}
