// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: internal/permission/subject.proto

package permissionpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Subject_GetAccessCodes_FullMethodName       = "/pmc.inapp.internal.permission.Subject/GetAccessCodes"
	Subject_GetAccessIds_FullMethodName         = "/pmc.inapp.internal.permission.Subject/GetAccessIds"
	Subject_GetInternalRoleCodes_FullMethodName = "/pmc.inapp.internal.permission.Subject/GetInternalRoleCodes"
)

// SubjectClient is the client API for Subject service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SubjectClient interface {
	GetAccessCodes(ctx context.Context, in *GetAccessRequest, opts ...grpc.CallOption) (*GetAccessCodesResponse, error)
	GetAccessIds(ctx context.Context, in *GetAccessRequest, opts ...grpc.CallOption) (*GetAccessIdsResponse, error)
	GetInternalRoleCodes(ctx context.Context, in *GetInternalRoleCodesRequest, opts ...grpc.CallOption) (*GetAccessCodesResponse, error)
}

type subjectClient struct {
	cc grpc.ClientConnInterface
}

func NewSubjectClient(cc grpc.ClientConnInterface) SubjectClient {
	return &subjectClient{cc}
}

func (c *subjectClient) GetAccessCodes(ctx context.Context, in *GetAccessRequest, opts ...grpc.CallOption) (*GetAccessCodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAccessCodesResponse)
	err := c.cc.Invoke(ctx, Subject_GetAccessCodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subjectClient) GetAccessIds(ctx context.Context, in *GetAccessRequest, opts ...grpc.CallOption) (*GetAccessIdsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAccessIdsResponse)
	err := c.cc.Invoke(ctx, Subject_GetAccessIds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subjectClient) GetInternalRoleCodes(ctx context.Context, in *GetInternalRoleCodesRequest, opts ...grpc.CallOption) (*GetAccessCodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAccessCodesResponse)
	err := c.cc.Invoke(ctx, Subject_GetInternalRoleCodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SubjectServer is the server API for Subject service.
// All implementations must embed UnimplementedSubjectServer
// for forward compatibility.
type SubjectServer interface {
	GetAccessCodes(context.Context, *GetAccessRequest) (*GetAccessCodesResponse, error)
	GetAccessIds(context.Context, *GetAccessRequest) (*GetAccessIdsResponse, error)
	GetInternalRoleCodes(context.Context, *GetInternalRoleCodesRequest) (*GetAccessCodesResponse, error)
	mustEmbedUnimplementedSubjectServer()
}

// UnimplementedSubjectServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSubjectServer struct{}

func (UnimplementedSubjectServer) GetAccessCodes(context.Context, *GetAccessRequest) (*GetAccessCodesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccessCodes not implemented")
}
func (UnimplementedSubjectServer) GetAccessIds(context.Context, *GetAccessRequest) (*GetAccessIdsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccessIds not implemented")
}
func (UnimplementedSubjectServer) GetInternalRoleCodes(context.Context, *GetInternalRoleCodesRequest) (*GetAccessCodesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInternalRoleCodes not implemented")
}
func (UnimplementedSubjectServer) mustEmbedUnimplementedSubjectServer() {}
func (UnimplementedSubjectServer) testEmbeddedByValue()                 {}

// UnsafeSubjectServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SubjectServer will
// result in compilation errors.
type UnsafeSubjectServer interface {
	mustEmbedUnimplementedSubjectServer()
}

func RegisterSubjectServer(s grpc.ServiceRegistrar, srv SubjectServer) {
	// If the following call pancis, it indicates UnimplementedSubjectServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Subject_ServiceDesc, srv)
}

func _Subject_GetAccessCodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubjectServer).GetAccessCodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Subject_GetAccessCodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubjectServer).GetAccessCodes(ctx, req.(*GetAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Subject_GetAccessIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubjectServer).GetAccessIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Subject_GetAccessIds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubjectServer).GetAccessIds(ctx, req.(*GetAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Subject_GetInternalRoleCodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInternalRoleCodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubjectServer).GetInternalRoleCodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Subject_GetInternalRoleCodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubjectServer).GetInternalRoleCodes(ctx, req.(*GetInternalRoleCodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Subject_ServiceDesc is the grpc.ServiceDesc for Subject service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Subject_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pmc.inapp.internal.permission.Subject",
	HandlerType: (*SubjectServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAccessCodes",
			Handler:    _Subject_GetAccessCodes_Handler,
		},
		{
			MethodName: "GetAccessIds",
			Handler:    _Subject_GetAccessIds_Handler,
		},
		{
			MethodName: "GetInternalRoleCodes",
			Handler:    _Subject_GetInternalRoleCodes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/permission/subject.proto",
}
