// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: internal/attachment/attachment.proto

package attachment

import (
	protobuf "pulse/helper/utils/pmc/protobuf"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ActionType int32

const (
	ActionType_UPLOAD_TYPE ActionType = 0
	ActionType_EXPORT_TYPE ActionType = 1
)

// Enum value maps for ActionType.
var (
	ActionType_name = map[int32]string{
		0: "UPLOAD_TYPE",
		1: "EXPORT_TYPE",
	}
	ActionType_value = map[string]int32{
		"UPLOAD_TYPE": 0,
		"EXPORT_TYPE": 1,
	}
)

func (x ActionType) Enum() *ActionType {
	p := new(ActionType)
	*p = x
	return p
}

func (x ActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActionType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_attachment_attachment_proto_enumTypes[0].Descriptor()
}

func (ActionType) Type() protoreflect.EnumType {
	return &file_internal_attachment_attachment_proto_enumTypes[0]
}

func (x ActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActionType.Descriptor instead.
func (ActionType) EnumDescriptor() ([]byte, []int) {
	return file_internal_attachment_attachment_proto_rawDescGZIP(), []int{0}
}

type FileInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=file_name,proto3" json:"file_name,omitempty"`
	FileData      []byte                 `protobuf:"bytes,2,opt,name=file_data,proto3" json:"file_data,omitempty"`
	FileSize      int64                  `protobuf:"varint,3,opt,name=file_size,proto3" json:"file_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	mi := &file_internal_attachment_attachment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_attachment_attachment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_internal_attachment_attachment_proto_rawDescGZIP(), []int{0}
}

func (x *FileInfo) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *FileInfo) GetFileData() []byte {
	if x != nil {
		return x.FileData
	}
	return nil
}

func (x *FileInfo) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

type UploadAttachmentRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Attachments      []*FileInfo            `protobuf:"bytes,1,rep,name=attachments,proto3" json:"attachments,omitempty"`
	ServiceName      string                 `protobuf:"bytes,2,opt,name=service_name,proto3" json:"service_name,omitempty"`
	Acl              *string                `protobuf:"bytes,3,opt,name=acl,proto3,oneof" json:"acl,omitempty"`
	IsOverride       *bool                  `protobuf:"varint,4,opt,name=is_override,proto3,oneof" json:"is_override,omitempty"`
	IsPresigned      *bool                  `protobuf:"varint,5,opt,name=is_presigned,proto3,oneof" json:"is_presigned,omitempty"`
	Duration         *durationpb.Duration   `protobuf:"bytes,6,opt,name=duration,proto3,oneof" json:"duration,omitempty"`
	BucketAlias      *string                `protobuf:"bytes,7,opt,name=bucket_alias,proto3,oneof" json:"bucket_alias,omitempty"`
	Action           *ActionType            `protobuf:"varint,8,opt,name=action,proto3,enum=pmc.inapp.storage.attachment.ActionType,oneof" json:"action,omitempty"`
	OriginalFilename *bool                  `protobuf:"varint,9,opt,name=original_filename,proto3,oneof" json:"original_filename,omitempty"`
	EmployeeId       *string                `protobuf:"bytes,10,opt,name=employee_id,proto3,oneof" json:"employee_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UploadAttachmentRequest) Reset() {
	*x = UploadAttachmentRequest{}
	mi := &file_internal_attachment_attachment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadAttachmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadAttachmentRequest) ProtoMessage() {}

func (x *UploadAttachmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_attachment_attachment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadAttachmentRequest.ProtoReflect.Descriptor instead.
func (*UploadAttachmentRequest) Descriptor() ([]byte, []int) {
	return file_internal_attachment_attachment_proto_rawDescGZIP(), []int{1}
}

func (x *UploadAttachmentRequest) GetAttachments() []*FileInfo {
	if x != nil {
		return x.Attachments
	}
	return nil
}

func (x *UploadAttachmentRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *UploadAttachmentRequest) GetAcl() string {
	if x != nil && x.Acl != nil {
		return *x.Acl
	}
	return ""
}

func (x *UploadAttachmentRequest) GetIsOverride() bool {
	if x != nil && x.IsOverride != nil {
		return *x.IsOverride
	}
	return false
}

func (x *UploadAttachmentRequest) GetIsPresigned() bool {
	if x != nil && x.IsPresigned != nil {
		return *x.IsPresigned
	}
	return false
}

func (x *UploadAttachmentRequest) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

func (x *UploadAttachmentRequest) GetBucketAlias() string {
	if x != nil && x.BucketAlias != nil {
		return *x.BucketAlias
	}
	return ""
}

func (x *UploadAttachmentRequest) GetAction() ActionType {
	if x != nil && x.Action != nil {
		return *x.Action
	}
	return ActionType_UPLOAD_TYPE
}

func (x *UploadAttachmentRequest) GetOriginalFilename() bool {
	if x != nil && x.OriginalFilename != nil {
		return *x.OriginalFilename
	}
	return false
}

func (x *UploadAttachmentRequest) GetEmployeeId() string {
	if x != nil && x.EmployeeId != nil {
		return *x.EmployeeId
	}
	return ""
}

type UploadAttachmentResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Attachments   []*UploadAttachmentItem `protobuf:"bytes,1,rep,name=attachments,proto3" json:"attachments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadAttachmentResponse) Reset() {
	*x = UploadAttachmentResponse{}
	mi := &file_internal_attachment_attachment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadAttachmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadAttachmentResponse) ProtoMessage() {}

func (x *UploadAttachmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_attachment_attachment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadAttachmentResponse.ProtoReflect.Descriptor instead.
func (*UploadAttachmentResponse) Descriptor() ([]byte, []int) {
	return file_internal_attachment_attachment_proto_rawDescGZIP(), []int{2}
}

func (x *UploadAttachmentResponse) GetAttachments() []*UploadAttachmentItem {
	if x != nil {
		return x.Attachments
	}
	return nil
}

type UploadAttachmentItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*UploadAttachmentItem_Url
	//	*UploadAttachmentItem_Error
	Response      isUploadAttachmentItem_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadAttachmentItem) Reset() {
	*x = UploadAttachmentItem{}
	mi := &file_internal_attachment_attachment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadAttachmentItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadAttachmentItem) ProtoMessage() {}

func (x *UploadAttachmentItem) ProtoReflect() protoreflect.Message {
	mi := &file_internal_attachment_attachment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadAttachmentItem.ProtoReflect.Descriptor instead.
func (*UploadAttachmentItem) Descriptor() ([]byte, []int) {
	return file_internal_attachment_attachment_proto_rawDescGZIP(), []int{3}
}

func (x *UploadAttachmentItem) GetResponse() isUploadAttachmentItem_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *UploadAttachmentItem) GetUrl() string {
	if x != nil {
		if x, ok := x.Response.(*UploadAttachmentItem_Url); ok {
			return x.Url
		}
	}
	return ""
}

func (x *UploadAttachmentItem) GetError() *protobuf.Status {
	if x != nil {
		if x, ok := x.Response.(*UploadAttachmentItem_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isUploadAttachmentItem_Response interface {
	isUploadAttachmentItem_Response()
}

type UploadAttachmentItem_Url struct {
	Url string `protobuf:"bytes,1,opt,name=url,proto3,oneof"`
}

type UploadAttachmentItem_Error struct {
	Error *protobuf.Status `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*UploadAttachmentItem_Url) isUploadAttachmentItem_Response() {}

func (*UploadAttachmentItem_Error) isUploadAttachmentItem_Response() {}

type PreSignedUrlsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Urls          []string               `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
	Duration      *durationpb.Duration   `protobuf:"bytes,2,opt,name=duration,proto3,oneof" json:"duration,omitempty"`
	IsPut         *bool                  `protobuf:"varint,3,opt,name=is_put,proto3,oneof" json:"is_put,omitempty"`
	BucketAlias   *string                `protobuf:"bytes,4,opt,name=bucket_alias,proto3,oneof" json:"bucket_alias,omitempty"`
	Action        *ActionType            `protobuf:"varint,5,opt,name=action,proto3,enum=pmc.inapp.storage.attachment.ActionType,oneof" json:"action,omitempty"`
	EmployeeId    *string                `protobuf:"bytes,6,opt,name=employee_id,proto3,oneof" json:"employee_id,omitempty"`
	ServiceName   string                 `protobuf:"bytes,7,opt,name=service_name,proto3" json:"service_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreSignedUrlsRequest) Reset() {
	*x = PreSignedUrlsRequest{}
	mi := &file_internal_attachment_attachment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreSignedUrlsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreSignedUrlsRequest) ProtoMessage() {}

func (x *PreSignedUrlsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_attachment_attachment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreSignedUrlsRequest.ProtoReflect.Descriptor instead.
func (*PreSignedUrlsRequest) Descriptor() ([]byte, []int) {
	return file_internal_attachment_attachment_proto_rawDescGZIP(), []int{4}
}

func (x *PreSignedUrlsRequest) GetUrls() []string {
	if x != nil {
		return x.Urls
	}
	return nil
}

func (x *PreSignedUrlsRequest) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

func (x *PreSignedUrlsRequest) GetIsPut() bool {
	if x != nil && x.IsPut != nil {
		return *x.IsPut
	}
	return false
}

func (x *PreSignedUrlsRequest) GetBucketAlias() string {
	if x != nil && x.BucketAlias != nil {
		return *x.BucketAlias
	}
	return ""
}

func (x *PreSignedUrlsRequest) GetAction() ActionType {
	if x != nil && x.Action != nil {
		return *x.Action
	}
	return ActionType_UPLOAD_TYPE
}

func (x *PreSignedUrlsRequest) GetEmployeeId() string {
	if x != nil && x.EmployeeId != nil {
		return *x.EmployeeId
	}
	return ""
}

func (x *PreSignedUrlsRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

type PreSignedUrlsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SignedUrls    []string               `protobuf:"bytes,1,rep,name=signed_urls,proto3" json:"signed_urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreSignedUrlsResponse) Reset() {
	*x = PreSignedUrlsResponse{}
	mi := &file_internal_attachment_attachment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreSignedUrlsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreSignedUrlsResponse) ProtoMessage() {}

func (x *PreSignedUrlsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_attachment_attachment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreSignedUrlsResponse.ProtoReflect.Descriptor instead.
func (*PreSignedUrlsResponse) Descriptor() ([]byte, []int) {
	return file_internal_attachment_attachment_proto_rawDescGZIP(), []int{5}
}

func (x *PreSignedUrlsResponse) GetSignedUrls() []string {
	if x != nil {
		return x.SignedUrls
	}
	return nil
}

var File_internal_attachment_attachment_proto protoreflect.FileDescriptor

const file_internal_attachment_attachment_proto_rawDesc = "" +
	"\n" +
	"$internal/attachment/attachment.proto\x12\x1cpmc.inapp.storage.attachment\x1a\x17validate/validate.proto\x1a\x19pmc/protobuf/errors.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1egoogle/protobuf/duration.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"d\n" +
	"\bFileInfo\x12\x1c\n" +
	"\tfile_name\x18\x01 \x01(\tR\tfile_name\x12\x1c\n" +
	"\tfile_data\x18\x02 \x01(\fR\tfile_data\x12\x1c\n" +
	"\tfile_size\x18\x03 \x01(\x03R\tfile_size\"\xf6\x04\n" +
	"\x17UploadAttachmentRequest\x12R\n" +
	"\vattachments\x18\x01 \x03(\v2&.pmc.inapp.storage.attachment.FileInfoB\b\xfaB\x05\x92\x01\x02\b\x01R\vattachments\x12\"\n" +
	"\fservice_name\x18\x02 \x01(\tR\fservice_name\x12\x15\n" +
	"\x03acl\x18\x03 \x01(\tH\x00R\x03acl\x88\x01\x01\x12%\n" +
	"\vis_override\x18\x04 \x01(\bH\x01R\vis_override\x88\x01\x01\x12'\n" +
	"\fis_presigned\x18\x05 \x01(\bH\x02R\fis_presigned\x88\x01\x01\x12:\n" +
	"\bduration\x18\x06 \x01(\v2\x19.google.protobuf.DurationH\x03R\bduration\x88\x01\x01\x12'\n" +
	"\fbucket_alias\x18\a \x01(\tH\x04R\fbucket_alias\x88\x01\x01\x12E\n" +
	"\x06action\x18\b \x01(\x0e2(.pmc.inapp.storage.attachment.ActionTypeH\x05R\x06action\x88\x01\x01\x121\n" +
	"\x11original_filename\x18\t \x01(\bH\x06R\x11original_filename\x88\x01\x01\x12%\n" +
	"\vemployee_id\x18\n" +
	" \x01(\tH\aR\vemployee_id\x88\x01\x01B\x06\n" +
	"\x04_aclB\x0e\n" +
	"\f_is_overrideB\x0f\n" +
	"\r_is_presignedB\v\n" +
	"\t_durationB\x0f\n" +
	"\r_bucket_aliasB\t\n" +
	"\a_actionB\x14\n" +
	"\x12_original_filenameB\x0e\n" +
	"\f_employee_id\"p\n" +
	"\x18UploadAttachmentResponse\x12T\n" +
	"\vattachments\x18\x01 \x03(\v22.pmc.inapp.storage.attachment.UploadAttachmentItemR\vattachments\"d\n" +
	"\x14UploadAttachmentItem\x12\x12\n" +
	"\x03url\x18\x01 \x01(\tH\x00R\x03url\x12,\n" +
	"\x05error\x18\x02 \x01(\v2\x14.pmc.protobuf.StatusH\x00R\x05errorB\n" +
	"\n" +
	"\bresponse\"\x9e\x03\n" +
	"\x14PreSignedUrlsRequest\x12.\n" +
	"\x04urls\x18\x01 \x03(\tB\x1a\xfaB\x17\x92\x01\x14\b\x01\x18\x01\"\x0er\fJ\a/inapp/\x88\x01\x01R\x04urls\x12:\n" +
	"\bduration\x18\x02 \x01(\v2\x19.google.protobuf.DurationH\x00R\bduration\x88\x01\x01\x12\x1b\n" +
	"\x06is_put\x18\x03 \x01(\bH\x01R\x06is_put\x88\x01\x01\x12'\n" +
	"\fbucket_alias\x18\x04 \x01(\tH\x02R\fbucket_alias\x88\x01\x01\x12E\n" +
	"\x06action\x18\x05 \x01(\x0e2(.pmc.inapp.storage.attachment.ActionTypeH\x03R\x06action\x88\x01\x01\x12%\n" +
	"\vemployee_id\x18\x06 \x01(\tH\x04R\vemployee_id\x88\x01\x01\x12\"\n" +
	"\fservice_name\x18\a \x01(\tR\fservice_nameB\v\n" +
	"\t_durationB\t\n" +
	"\a_is_putB\x0f\n" +
	"\r_bucket_aliasB\t\n" +
	"\a_actionB\x0e\n" +
	"\f_employee_id\"9\n" +
	"\x15PreSignedUrlsResponse\x12 \n" +
	"\vsigned_urls\x18\x01 \x03(\tR\vsigned_urls*.\n" +
	"\n" +
	"ActionType\x12\x0f\n" +
	"\vUPLOAD_TYPE\x10\x00\x12\x0f\n" +
	"\vEXPORT_TYPE\x10\x012\xf8\x02\n" +
	"\n" +
	"Attachment\x12\x93\x01\n" +
	"\x06Upload\x125.pmc.inapp.storage.attachment.UploadAttachmentRequest\x1a6.pmc.inapp.storage.attachment.UploadAttachmentResponse\"\x1a\x92A\x17b\x15\n" +
	"\x13\n" +
	"\rAuthorization\x12\x02\n" +
	"\x00\x12\xd3\x01\n" +
	"\rPreSignedUrls\x122.pmc.inapp.storage.attachment.PreSignedUrlsRequest\x1a3.pmc.inapp.storage.attachment.PreSignedUrlsResponse\"Y\x92A\x17b\x15\n" +
	"\x13\n" +
	"\rAuthorization\x12\x02\n" +
	"\x00\x82\xd3\xe4\x93\x029:\x01*\"4/cloud-storage-svc/api/v1/attachment/pre-signed-urlsB\x80\x03\x92A\x9c\x02\x12\xbb\x01\n" +
	"\x15Cloud Storage Service\"=\n" +
	"\x18Pharmacity Internal Team\x12!https://github.com/Pharmacity-JSC*^\n" +
	"\x14BSD 3-Clause License\x12Fhttps://github.com/grpc-ecosystem/grpc-gateway/blob/master/LICENSE.txt2\x031.0*\x02\x02\x012\x10application/json:\x10application/jsonZ4\n" +
	"2\n" +
	"\rAuthorization\x12!\b\x02\x12\fBearer Token\x1a\rAuthorization \x02Z^dev.azure.com/PHARMACITYJSC/PharmacityLibrary/_git/pmc-inapp-helper.git/v2/internal/attachmentb\x06proto3"

var (
	file_internal_attachment_attachment_proto_rawDescOnce sync.Once
	file_internal_attachment_attachment_proto_rawDescData []byte
)

func file_internal_attachment_attachment_proto_rawDescGZIP() []byte {
	file_internal_attachment_attachment_proto_rawDescOnce.Do(func() {
		file_internal_attachment_attachment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_attachment_attachment_proto_rawDesc), len(file_internal_attachment_attachment_proto_rawDesc)))
	})
	return file_internal_attachment_attachment_proto_rawDescData
}

var file_internal_attachment_attachment_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_attachment_attachment_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_internal_attachment_attachment_proto_goTypes = []any{
	(ActionType)(0),                  // 0: pmc.inapp.storage.attachment.ActionType
	(*FileInfo)(nil),                 // 1: pmc.inapp.storage.attachment.FileInfo
	(*UploadAttachmentRequest)(nil),  // 2: pmc.inapp.storage.attachment.UploadAttachmentRequest
	(*UploadAttachmentResponse)(nil), // 3: pmc.inapp.storage.attachment.UploadAttachmentResponse
	(*UploadAttachmentItem)(nil),     // 4: pmc.inapp.storage.attachment.UploadAttachmentItem
	(*PreSignedUrlsRequest)(nil),     // 5: pmc.inapp.storage.attachment.PreSignedUrlsRequest
	(*PreSignedUrlsResponse)(nil),    // 6: pmc.inapp.storage.attachment.PreSignedUrlsResponse
	(*durationpb.Duration)(nil),      // 7: google.protobuf.Duration
	(*protobuf.Status)(nil),          // 8: pmc.protobuf.Status
}
var file_internal_attachment_attachment_proto_depIdxs = []int32{
	1, // 0: pmc.inapp.storage.attachment.UploadAttachmentRequest.attachments:type_name -> pmc.inapp.storage.attachment.FileInfo
	7, // 1: pmc.inapp.storage.attachment.UploadAttachmentRequest.duration:type_name -> google.protobuf.Duration
	0, // 2: pmc.inapp.storage.attachment.UploadAttachmentRequest.action:type_name -> pmc.inapp.storage.attachment.ActionType
	4, // 3: pmc.inapp.storage.attachment.UploadAttachmentResponse.attachments:type_name -> pmc.inapp.storage.attachment.UploadAttachmentItem
	8, // 4: pmc.inapp.storage.attachment.UploadAttachmentItem.error:type_name -> pmc.protobuf.Status
	7, // 5: pmc.inapp.storage.attachment.PreSignedUrlsRequest.duration:type_name -> google.protobuf.Duration
	0, // 6: pmc.inapp.storage.attachment.PreSignedUrlsRequest.action:type_name -> pmc.inapp.storage.attachment.ActionType
	2, // 7: pmc.inapp.storage.attachment.Attachment.Upload:input_type -> pmc.inapp.storage.attachment.UploadAttachmentRequest
	5, // 8: pmc.inapp.storage.attachment.Attachment.PreSignedUrls:input_type -> pmc.inapp.storage.attachment.PreSignedUrlsRequest
	3, // 9: pmc.inapp.storage.attachment.Attachment.Upload:output_type -> pmc.inapp.storage.attachment.UploadAttachmentResponse
	6, // 10: pmc.inapp.storage.attachment.Attachment.PreSignedUrls:output_type -> pmc.inapp.storage.attachment.PreSignedUrlsResponse
	9, // [9:11] is the sub-list for method output_type
	7, // [7:9] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_internal_attachment_attachment_proto_init() }
func file_internal_attachment_attachment_proto_init() {
	if File_internal_attachment_attachment_proto != nil {
		return
	}
	file_internal_attachment_attachment_proto_msgTypes[1].OneofWrappers = []any{}
	file_internal_attachment_attachment_proto_msgTypes[3].OneofWrappers = []any{
		(*UploadAttachmentItem_Url)(nil),
		(*UploadAttachmentItem_Error)(nil),
	}
	file_internal_attachment_attachment_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_attachment_attachment_proto_rawDesc), len(file_internal_attachment_attachment_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_attachment_attachment_proto_goTypes,
		DependencyIndexes: file_internal_attachment_attachment_proto_depIdxs,
		EnumInfos:         file_internal_attachment_attachment_proto_enumTypes,
		MessageInfos:      file_internal_attachment_attachment_proto_msgTypes,
	}.Build()
	File_internal_attachment_attachment_proto = out.File
	file_internal_attachment_attachment_proto_goTypes = nil
	file_internal_attachment_attachment_proto_depIdxs = nil
}
