// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.26.1
// source: api/incident/incident.proto

package incidentpb

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	common "pulse/api/common"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IncidentStatus int32

const (
	IncidentStatus_INCIDENT_STATUS_UNSPECIFIED   IncidentStatus = 0
	IncidentStatus_INCIDENT_STATUS_OPEN          IncidentStatus = 1
	IncidentStatus_INCIDENT_STATUS_INVESTIGATING IncidentStatus = 2
	IncidentStatus_INCIDENT_STATUS_RESOLVING     IncidentStatus = 3
	IncidentStatus_INCIDENT_STATUS_RESOLVED      IncidentStatus = 4
	IncidentStatus_INCIDENT_STATUS_CLOSED        IncidentStatus = 5
)

// Enum value maps for IncidentStatus.
var (
	IncidentStatus_name = map[int32]string{
		0: "INCIDENT_STATUS_UNSPECIFIED",
		1: "INCIDENT_STATUS_OPEN",
		2: "INCIDENT_STATUS_INVESTIGATING",
		3: "INCIDENT_STATUS_RESOLVING",
		4: "INCIDENT_STATUS_RESOLVED",
		5: "INCIDENT_STATUS_CLOSED",
	}
	IncidentStatus_value = map[string]int32{
		"INCIDENT_STATUS_UNSPECIFIED":   0,
		"INCIDENT_STATUS_OPEN":          1,
		"INCIDENT_STATUS_INVESTIGATING": 2,
		"INCIDENT_STATUS_RESOLVING":     3,
		"INCIDENT_STATUS_RESOLVED":      4,
		"INCIDENT_STATUS_CLOSED":        5,
	}
)

func (x IncidentStatus) Enum() *IncidentStatus {
	p := new(IncidentStatus)
	*p = x
	return p
}

func (x IncidentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IncidentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_incident_incident_proto_enumTypes[0].Descriptor()
}

func (IncidentStatus) Type() protoreflect.EnumType {
	return &file_api_incident_incident_proto_enumTypes[0]
}

func (x IncidentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IncidentStatus.Descriptor instead.
func (IncidentStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_incident_incident_proto_rawDescGZIP(), []int{0}
}

type Severity int32

const (
	Severity_SEVERITY_UNSPECIFIED Severity = 0
	Severity_SEVERITY_LOW         Severity = 1
	Severity_SEVERITY_MEDIUM      Severity = 2
	Severity_SEVERITY_HIGH        Severity = 3
	Severity_SEVERITY_CRITICAL    Severity = 4
)

// Enum value maps for Severity.
var (
	Severity_name = map[int32]string{
		0: "SEVERITY_UNSPECIFIED",
		1: "SEVERITY_LOW",
		2: "SEVERITY_MEDIUM",
		3: "SEVERITY_HIGH",
		4: "SEVERITY_CRITICAL",
	}
	Severity_value = map[string]int32{
		"SEVERITY_UNSPECIFIED": 0,
		"SEVERITY_LOW":         1,
		"SEVERITY_MEDIUM":      2,
		"SEVERITY_HIGH":        3,
		"SEVERITY_CRITICAL":    4,
	}
)

func (x Severity) Enum() *Severity {
	p := new(Severity)
	*p = x
	return p
}

func (x Severity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Severity) Descriptor() protoreflect.EnumDescriptor {
	return file_api_incident_incident_proto_enumTypes[1].Descriptor()
}

func (Severity) Type() protoreflect.EnumType {
	return &file_api_incident_incident_proto_enumTypes[1]
}

func (x Severity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Severity.Descriptor instead.
func (Severity) EnumDescriptor() ([]byte, []int) {
	return file_api_incident_incident_proto_rawDescGZIP(), []int{1}
}

// ResolutionCategory classifies the root cause when resolving an incident.
type ResolutionCategory int32

const (
	ResolutionCategory_RESOLUTION_CATEGORY_UNSPECIFIED ResolutionCategory = 0
	ResolutionCategory_RESOLUTION_CATEGORY_CODE_BUG    ResolutionCategory = 1
	ResolutionCategory_RESOLUTION_CATEGORY_CONFIG      ResolutionCategory = 2
	ResolutionCategory_RESOLUTION_CATEGORY_INFRA       ResolutionCategory = 3
	ResolutionCategory_RESOLUTION_CATEGORY_EXTERNAL    ResolutionCategory = 4
)

// Enum value maps for ResolutionCategory.
var (
	ResolutionCategory_name = map[int32]string{
		0: "RESOLUTION_CATEGORY_UNSPECIFIED",
		1: "RESOLUTION_CATEGORY_CODE_BUG",
		2: "RESOLUTION_CATEGORY_CONFIG",
		3: "RESOLUTION_CATEGORY_INFRA",
		4: "RESOLUTION_CATEGORY_EXTERNAL",
	}
	ResolutionCategory_value = map[string]int32{
		"RESOLUTION_CATEGORY_UNSPECIFIED": 0,
		"RESOLUTION_CATEGORY_CODE_BUG":    1,
		"RESOLUTION_CATEGORY_CONFIG":      2,
		"RESOLUTION_CATEGORY_INFRA":       3,
		"RESOLUTION_CATEGORY_EXTERNAL":    4,
	}
)

func (x ResolutionCategory) Enum() *ResolutionCategory {
	p := new(ResolutionCategory)
	*p = x
	return p
}

func (x ResolutionCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResolutionCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_api_incident_incident_proto_enumTypes[2].Descriptor()
}

func (ResolutionCategory) Type() protoreflect.EnumType {
	return &file_api_incident_incident_proto_enumTypes[2]
}

func (x ResolutionCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResolutionCategory.Descriptor instead.
func (ResolutionCategory) EnumDescriptor() ([]byte, []int) {
	return file_api_incident_incident_proto_rawDescGZIP(), []int{2}
}

type Incident struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ServiceName   string                 `protobuf:"bytes,4,opt,name=service_name,proto3" json:"service_name,omitempty"`
	Fingerprint   string                 `protobuf:"bytes,5,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	Status        IncidentStatus         `protobuf:"varint,6,opt,name=status,proto3,enum=pulse.incident.IncidentStatus" json:"status,omitempty"`
	Severity      Severity               `protobuf:"varint,7,opt,name=severity,proto3,enum=pulse.incident.Severity" json:"severity,omitempty"`
	RcaSummary    string                 `protobuf:"bytes,8,opt,name=rca_summary,proto3" json:"rca_summary,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,proto3" json:"updated_at,omitempty"`
	ResolvedAt    *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=resolved_at,proto3" json:"resolved_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Incident) Reset() {
	*x = Incident{}
	mi := &file_api_incident_incident_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Incident) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Incident) ProtoMessage() {}

func (x *Incident) ProtoReflect() protoreflect.Message {
	mi := &file_api_incident_incident_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Incident.ProtoReflect.Descriptor instead.
func (*Incident) Descriptor() ([]byte, []int) {
	return file_api_incident_incident_proto_rawDescGZIP(), []int{0}
}

func (x *Incident) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Incident) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Incident) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Incident) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *Incident) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *Incident) GetStatus() IncidentStatus {
	if x != nil {
		return x.Status
	}
	return IncidentStatus_INCIDENT_STATUS_UNSPECIFIED
}

func (x *Incident) GetSeverity() Severity {
	if x != nil {
		return x.Severity
	}
	return Severity_SEVERITY_UNSPECIFIED
}

func (x *Incident) GetRcaSummary() string {
	if x != nil {
		return x.RcaSummary
	}
	return ""
}

func (x *Incident) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Incident) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Incident) GetResolvedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ResolvedAt
	}
	return nil
}

type ListIncidentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Status        IncidentStatus         `protobuf:"varint,3,opt,name=status,proto3,enum=pulse.incident.IncidentStatus" json:"status,omitempty"`
	Severity      Severity               `protobuf:"varint,4,opt,name=severity,proto3,enum=pulse.incident.Severity" json:"severity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIncidentsRequest) Reset() {
	*x = ListIncidentsRequest{}
	mi := &file_api_incident_incident_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIncidentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIncidentsRequest) ProtoMessage() {}

func (x *ListIncidentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_incident_incident_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIncidentsRequest.ProtoReflect.Descriptor instead.
func (*ListIncidentsRequest) Descriptor() ([]byte, []int) {
	return file_api_incident_incident_proto_rawDescGZIP(), []int{1}
}

func (x *ListIncidentsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListIncidentsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListIncidentsRequest) GetStatus() IncidentStatus {
	if x != nil {
		return x.Status
	}
	return IncidentStatus_INCIDENT_STATUS_UNSPECIFIED
}

func (x *ListIncidentsRequest) GetSeverity() Severity {
	if x != nil {
		return x.Severity
	}
	return Severity_SEVERITY_UNSPECIFIED
}

type ListIncidentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Incident            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Pagination    *common.Pagination     `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIncidentsResponse) Reset() {
	*x = ListIncidentsResponse{}
	mi := &file_api_incident_incident_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIncidentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIncidentsResponse) ProtoMessage() {}

func (x *ListIncidentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_incident_incident_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIncidentsResponse.ProtoReflect.Descriptor instead.
func (*ListIncidentsResponse) Descriptor() ([]byte, []int) {
	return file_api_incident_incident_proto_rawDescGZIP(), []int{2}
}

func (x *ListIncidentsResponse) GetItems() []*Incident {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListIncidentsResponse) GetPagination() *common.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type GetIncidentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIncidentRequest) Reset() {
	*x = GetIncidentRequest{}
	mi := &file_api_incident_incident_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIncidentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIncidentRequest) ProtoMessage() {}

func (x *GetIncidentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_incident_incident_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIncidentRequest.ProtoReflect.Descriptor instead.
func (*GetIncidentRequest) Descriptor() ([]byte, []int) {
	return file_api_incident_incident_proto_rawDescGZIP(), []int{3}
}

func (x *GetIncidentRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetIncidentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Incident      *Incident              `protobuf:"bytes,1,opt,name=incident,proto3" json:"incident,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIncidentResponse) Reset() {
	*x = GetIncidentResponse{}
	mi := &file_api_incident_incident_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIncidentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIncidentResponse) ProtoMessage() {}

func (x *GetIncidentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_incident_incident_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIncidentResponse.ProtoReflect.Descriptor instead.
func (*GetIncidentResponse) Descriptor() ([]byte, []int) {
	return file_api_incident_incident_proto_rawDescGZIP(), []int{4}
}

func (x *GetIncidentResponse) GetIncident() *Incident {
	if x != nil {
		return x.Incident
	}
	return nil
}

type UpdateIncidentStatusRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status             IncidentStatus         `protobuf:"varint,2,opt,name=status,proto3,enum=pulse.incident.IncidentStatus" json:"status,omitempty"`
	ResolutionCategory ResolutionCategory     `protobuf:"varint,3,opt,name=resolution_category,proto3,enum=pulse.incident.ResolutionCategory" json:"resolution_category,omitempty"`
	ResolutionNotes    string                 `protobuf:"bytes,4,opt,name=resolution_notes,proto3" json:"resolution_notes,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UpdateIncidentStatusRequest) Reset() {
	*x = UpdateIncidentStatusRequest{}
	mi := &file_api_incident_incident_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateIncidentStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateIncidentStatusRequest) ProtoMessage() {}

func (x *UpdateIncidentStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_incident_incident_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateIncidentStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateIncidentStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_incident_incident_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateIncidentStatusRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateIncidentStatusRequest) GetStatus() IncidentStatus {
	if x != nil {
		return x.Status
	}
	return IncidentStatus_INCIDENT_STATUS_UNSPECIFIED
}

func (x *UpdateIncidentStatusRequest) GetResolutionCategory() ResolutionCategory {
	if x != nil {
		return x.ResolutionCategory
	}
	return ResolutionCategory_RESOLUTION_CATEGORY_UNSPECIFIED
}

func (x *UpdateIncidentStatusRequest) GetResolutionNotes() string {
	if x != nil {
		return x.ResolutionNotes
	}
	return ""
}

type UpdateIncidentStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Incident      *Incident              `protobuf:"bytes,1,opt,name=incident,proto3" json:"incident,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateIncidentStatusResponse) Reset() {
	*x = UpdateIncidentStatusResponse{}
	mi := &file_api_incident_incident_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateIncidentStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateIncidentStatusResponse) ProtoMessage() {}

func (x *UpdateIncidentStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_incident_incident_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateIncidentStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateIncidentStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_incident_incident_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateIncidentStatusResponse) GetIncident() *Incident {
	if x != nil {
		return x.Incident
	}
	return nil
}

type TriggerRCARequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerRCARequest) Reset() {
	*x = TriggerRCARequest{}
	mi := &file_api_incident_incident_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerRCARequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerRCARequest) ProtoMessage() {}

func (x *TriggerRCARequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_incident_incident_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerRCARequest.ProtoReflect.Descriptor instead.
func (*TriggerRCARequest) Descriptor() ([]byte, []int) {
	return file_api_incident_incident_proto_rawDescGZIP(), []int{7}
}

func (x *TriggerRCARequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type TriggerRCAResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	RcaSummary string                 `protobuf:"bytes,1,opt,name=rca_summary,proto3" json:"rca_summary,omitempty"`
	// cached is true when the result was served from L1 (Redis) or L2 (DB) cache.
	Cached        bool `protobuf:"varint,2,opt,name=cached,proto3" json:"cached,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerRCAResponse) Reset() {
	*x = TriggerRCAResponse{}
	mi := &file_api_incident_incident_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerRCAResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerRCAResponse) ProtoMessage() {}

func (x *TriggerRCAResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_incident_incident_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerRCAResponse.ProtoReflect.Descriptor instead.
func (*TriggerRCAResponse) Descriptor() ([]byte, []int) {
	return file_api_incident_incident_proto_rawDescGZIP(), []int{8}
}

func (x *TriggerRCAResponse) GetRcaSummary() string {
	if x != nil {
		return x.RcaSummary
	}
	return ""
}

func (x *TriggerRCAResponse) GetCached() bool {
	if x != nil {
		return x.Cached
	}
	return false
}

var File_api_incident_incident_proto protoreflect.FileDescriptor

const file_api_incident_incident_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/incident/incident.proto\x12\x0epulse.incident\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17validate/validate.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x17api/common/common.proto\"\xde\x03\n" +
	"\bIncident\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\"\n" +
	"\fservice_name\x18\x04 \x01(\tR\fservice_name\x12 \n" +
	"\vfingerprint\x18\x05 \x01(\tR\vfingerprint\x126\n" +
	"\x06status\x18\x06 \x01(\x0e2\x1e.pulse.incident.IncidentStatusR\x06status\x124\n" +
	"\bseverity\x18\a \x01(\x0e2\x18.pulse.incident.SeverityR\bseverity\x12 \n" +
	"\vrca_summary\x18\b \x01(\tR\vrca_summary\x12:\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"created_at\x12:\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updated_at\x12<\n" +
	"\vresolved_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\vresolved_at\"\xae\x01\n" +
	"\x14ListIncidentsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x126\n" +
	"\x06status\x18\x03 \x01(\x0e2\x1e.pulse.incident.IncidentStatusR\x06status\x124\n" +
	"\bseverity\x18\x04 \x01(\x0e2\x18.pulse.incident.SeverityR\bseverity\"\x81\x01\n" +
	"\x15ListIncidentsResponse\x12.\n" +
	"\x05items\x18\x01 \x03(\v2\x18.pulse.incident.IncidentR\x05items\x128\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x18.pulse.common.PaginationR\n" +
	"pagination\"-\n" +
	"\x12GetIncidentRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x02id\"K\n" +
	"\x13GetIncidentResponse\x124\n" +
	"\bincident\x18\x01 \x01(\v2\x18.pulse.incident.IncidentR\bincident\"\xfa\x01\n" +
	"\x1bUpdateIncidentStatusRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x02id\x12@\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1e.pulse.incident.IncidentStatusB\b\xfaB\x05\x82\x01\x02\x10\x01R\x06status\x12T\n" +
	"\x13resolution_category\x18\x03 \x01(\x0e2\".pulse.incident.ResolutionCategoryR\x13resolution_category\x12*\n" +
	"\x10resolution_notes\x18\x04 \x01(\tR\x10resolution_notes\"T\n" +
	"\x1cUpdateIncidentStatusResponse\x124\n" +
	"\bincident\x18\x01 \x01(\v2\x18.pulse.incident.IncidentR\bincident\",\n" +
	"\x11TriggerRCARequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x02id\"N\n" +
	"\x12TriggerRCAResponse\x12 \n" +
	"\vrca_summary\x18\x01 \x01(\tR\vrca_summary\x12\x16\n" +
	"\x06cached\x18\x02 \x01(\bR\x06cached*\xc7\x01\n" +
	"\x0eIncidentStatus\x12\x1f\n" +
	"\x1bINCIDENT_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14INCIDENT_STATUS_OPEN\x10\x01\x12!\n" +
	"\x1dINCIDENT_STATUS_INVESTIGATING\x10\x02\x12\x1d\n" +
	"\x19INCIDENT_STATUS_RESOLVING\x10\x03\x12\x1c\n" +
	"\x18INCIDENT_STATUS_RESOLVED\x10\x04\x12\x1a\n" +
	"\x16INCIDENT_STATUS_CLOSED\x10\x05*u\n" +
	"\bSeverity\x12\x18\n" +
	"\x14SEVERITY_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fSEVERITY_LOW\x10\x01\x12\x13\n" +
	"\x0fSEVERITY_MEDIUM\x10\x02\x12\x11\n" +
	"\rSEVERITY_HIGH\x10\x03\x12\x15\n" +
	"\x11SEVERITY_CRITICAL\x10\x04*\xbc\x01\n" +
	"\x12ResolutionCategory\x12#\n" +
	"\x1fRESOLUTION_CATEGORY_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cRESOLUTION_CATEGORY_CODE_BUG\x10\x01\x12\x1e\n" +
	"\x1aRESOLUTION_CATEGORY_CONFIG\x10\x02\x12\x1d\n" +
	"\x19RESOLUTION_CATEGORY_INFRA\x10\x03\x12 \n" +
	"\x1cRESOLUTION_CATEGORY_EXTERNAL\x10\x042\xac\x05\n" +
	"\x0fIncidentService\x12\x91\x01\n" +
	"\rListIncidents\x12$.pulse.incident.ListIncidentsRequest\x1a%.pulse.incident.ListIncidentsResponse\"3\x92A\x1b\n" +
	"\tIncidents\x12\x0eList incidents\x82\xd3\xe4\x93\x02\x0f\x12\r/v1/incidents\x12\x94\x01\n" +
	"\vGetIncident\x12\".pulse.incident.GetIncidentRequest\x1a#.pulse.incident.GetIncidentResponse\"<\x92A\x1f\n" +
	"\tIncidents\x12\x12Get incident by ID\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/incidents/{id}\x12\xbd\x01\n" +
	"\x14UpdateIncidentStatus\x12+.pulse.incident.UpdateIncidentStatusRequest\x1a,.pulse.incident.UpdateIncidentStatusResponse\"J\x92A#\n" +
	"\tIncidents\x12\x16Update incident status\x82\xd3\xe4\x93\x02\x1e:\x01*2\x19/v1/incidents/{id}/status\x12\xad\x01\n" +
	"\n" +
	"TriggerRCA\x12!.pulse.incident.TriggerRCARequest\x1a\".pulse.incident.TriggerRCAResponse\"X\x92A4\n" +
	"\tIncidents\x12'Trigger or retrieve RCA for an incident\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/v1/incidents/{id}/rcaB\x9c\x01\x92Az\x12\x19\n" +
	"\x12Pulse Incident API2\x031.0*\x02\x01\x022\x10application/json:\x10application/jsonZ5\n" +
	"3\n" +
	"\n" +
	"BearerAuth\x12%\b\x02\x12\x10Bearer JWT token\x1a\rAuthorization \x02Z\x1dpulse/api/incident;incidentpbb\x06proto3"

var (
	file_api_incident_incident_proto_rawDescOnce sync.Once
	file_api_incident_incident_proto_rawDescData []byte
)

func file_api_incident_incident_proto_rawDescGZIP() []byte {
	file_api_incident_incident_proto_rawDescOnce.Do(func() {
		file_api_incident_incident_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_incident_incident_proto_rawDesc), len(file_api_incident_incident_proto_rawDesc)))
	})
	return file_api_incident_incident_proto_rawDescData
}

var file_api_incident_incident_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_api_incident_incident_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_incident_incident_proto_goTypes = []any{
	(IncidentStatus)(0),                  // 0: pulse.incident.IncidentStatus
	(Severity)(0),                        // 1: pulse.incident.Severity
	(ResolutionCategory)(0),              // 2: pulse.incident.ResolutionCategory
	(*Incident)(nil),                     // 3: pulse.incident.Incident
	(*ListIncidentsRequest)(nil),         // 4: pulse.incident.ListIncidentsRequest
	(*ListIncidentsResponse)(nil),        // 5: pulse.incident.ListIncidentsResponse
	(*GetIncidentRequest)(nil),           // 6: pulse.incident.GetIncidentRequest
	(*GetIncidentResponse)(nil),          // 7: pulse.incident.GetIncidentResponse
	(*UpdateIncidentStatusRequest)(nil),  // 8: pulse.incident.UpdateIncidentStatusRequest
	(*UpdateIncidentStatusResponse)(nil), // 9: pulse.incident.UpdateIncidentStatusResponse
	(*TriggerRCARequest)(nil),            // 10: pulse.incident.TriggerRCARequest
	(*TriggerRCAResponse)(nil),           // 11: pulse.incident.TriggerRCAResponse
	(*timestamppb.Timestamp)(nil),        // 12: google.protobuf.Timestamp
	(*common.Pagination)(nil),            // 13: pulse.common.Pagination
}
var file_api_incident_incident_proto_depIdxs = []int32{
	0,  // 0: pulse.incident.Incident.status:type_name -> pulse.incident.IncidentStatus
	1,  // 1: pulse.incident.Incident.severity:type_name -> pulse.incident.Severity
	12, // 2: pulse.incident.Incident.created_at:type_name -> google.protobuf.Timestamp
	12, // 3: pulse.incident.Incident.updated_at:type_name -> google.protobuf.Timestamp
	12, // 4: pulse.incident.Incident.resolved_at:type_name -> google.protobuf.Timestamp
	0,  // 5: pulse.incident.ListIncidentsRequest.status:type_name -> pulse.incident.IncidentStatus
	1,  // 6: pulse.incident.ListIncidentsRequest.severity:type_name -> pulse.incident.Severity
	3,  // 7: pulse.incident.ListIncidentsResponse.items:type_name -> pulse.incident.Incident
	13, // 8: pulse.incident.ListIncidentsResponse.pagination:type_name -> pulse.common.Pagination
	3,  // 9: pulse.incident.GetIncidentResponse.incident:type_name -> pulse.incident.Incident
	0,  // 10: pulse.incident.UpdateIncidentStatusRequest.status:type_name -> pulse.incident.IncidentStatus
	2,  // 11: pulse.incident.UpdateIncidentStatusRequest.resolution_category:type_name -> pulse.incident.ResolutionCategory
	3,  // 12: pulse.incident.UpdateIncidentStatusResponse.incident:type_name -> pulse.incident.Incident
	4,  // 13: pulse.incident.IncidentService.ListIncidents:input_type -> pulse.incident.ListIncidentsRequest
	6,  // 14: pulse.incident.IncidentService.GetIncident:input_type -> pulse.incident.GetIncidentRequest
	8,  // 15: pulse.incident.IncidentService.UpdateIncidentStatus:input_type -> pulse.incident.UpdateIncidentStatusRequest
	10, // 16: pulse.incident.IncidentService.TriggerRCA:input_type -> pulse.incident.TriggerRCARequest
	5,  // 17: pulse.incident.IncidentService.ListIncidents:output_type -> pulse.incident.ListIncidentsResponse
	7,  // 18: pulse.incident.IncidentService.GetIncident:output_type -> pulse.incident.GetIncidentResponse
	9,  // 19: pulse.incident.IncidentService.UpdateIncidentStatus:output_type -> pulse.incident.UpdateIncidentStatusResponse
	11, // 20: pulse.incident.IncidentService.TriggerRCA:output_type -> pulse.incident.TriggerRCAResponse
	17, // [17:21] is the sub-list for method output_type
	13, // [13:17] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_api_incident_incident_proto_init() }
func file_api_incident_incident_proto_init() {
	if File_api_incident_incident_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_incident_incident_proto_rawDesc), len(file_api_incident_incident_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_incident_incident_proto_goTypes,
		DependencyIndexes: file_api_incident_incident_proto_depIdxs,
		EnumInfos:         file_api_incident_incident_proto_enumTypes,
		MessageInfos:      file_api_incident_incident_proto_msgTypes,
	}.Build()
	File_api_incident_incident_proto = out.File
	file_api_incident_incident_proto_goTypes = nil
	file_api_incident_incident_proto_depIdxs = nil
}
