// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/incident/incident.proto

package incidentpb

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Incident with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Incident) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Incident with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in IncidentMultiError, or nil
// if none found.
func (m *Incident) ValidateAll() error {
	return m.validate(true)
}

func (m *Incident) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Title

	// no validation rules for Description

	// no validation rules for ServiceName

	// no validation rules for Fingerprint

	// no validation rules for Status

	// no validation rules for Severity

	// no validation rules for RcaSummary

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, IncidentValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, IncidentValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return IncidentValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetUpdatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, IncidentValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, IncidentValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUpdatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return IncidentValidationError{
				field:  "UpdatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetResolvedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, IncidentValidationError{
					field:  "ResolvedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, IncidentValidationError{
					field:  "ResolvedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetResolvedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return IncidentValidationError{
				field:  "ResolvedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return IncidentMultiError(errors)
	}

	return nil
}

// IncidentMultiError is an error wrapping multiple validation errors returned
// by Incident.ValidateAll() if the designated constraints aren't met.
type IncidentMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m IncidentMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m IncidentMultiError) AllErrors() []error { return m }

// IncidentValidationError is the validation error returned by
// Incident.Validate if the designated constraints aren't met.
type IncidentValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e IncidentValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e IncidentValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e IncidentValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e IncidentValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e IncidentValidationError) ErrorName() string { return "IncidentValidationError" }

// Error satisfies the builtin error interface
func (e IncidentValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sIncident.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = IncidentValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = IncidentValidationError{}

// Validate checks the field values on ListIncidentsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListIncidentsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListIncidentsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListIncidentsRequestMultiError, or nil if none found.
func (m *ListIncidentsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListIncidentsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Page

	// no validation rules for Limit

	// no validation rules for Status

	// no validation rules for Severity

	if len(errors) > 0 {
		return ListIncidentsRequestMultiError(errors)
	}

	return nil
}

// ListIncidentsRequestMultiError is an error wrapping multiple validation
// errors returned by ListIncidentsRequest.ValidateAll() if the designated
// constraints aren't met.
type ListIncidentsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListIncidentsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListIncidentsRequestMultiError) AllErrors() []error { return m }

// ListIncidentsRequestValidationError is the validation error returned by
// ListIncidentsRequest.Validate if the designated constraints aren't met.
type ListIncidentsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListIncidentsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListIncidentsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListIncidentsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListIncidentsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListIncidentsRequestValidationError) ErrorName() string {
	return "ListIncidentsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListIncidentsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListIncidentsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListIncidentsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListIncidentsRequestValidationError{}

// Validate checks the field values on ListIncidentsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListIncidentsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListIncidentsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListIncidentsResponseMultiError, or nil if none found.
func (m *ListIncidentsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListIncidentsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetItems() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListIncidentsResponseValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListIncidentsResponseValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListIncidentsResponseValidationError{
					field:  fmt.Sprintf("Items[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if all {
		switch v := interface{}(m.GetPagination()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ListIncidentsResponseValidationError{
					field:  "Pagination",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ListIncidentsResponseValidationError{
					field:  "Pagination",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPagination()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListIncidentsResponseValidationError{
				field:  "Pagination",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ListIncidentsResponseMultiError(errors)
	}

	return nil
}

// ListIncidentsResponseMultiError is an error wrapping multiple validation
// errors returned by ListIncidentsResponse.ValidateAll() if the designated
// constraints aren't met.
type ListIncidentsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListIncidentsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListIncidentsResponseMultiError) AllErrors() []error { return m }

// ListIncidentsResponseValidationError is the validation error returned by
// ListIncidentsResponse.Validate if the designated constraints aren't met.
type ListIncidentsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListIncidentsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListIncidentsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListIncidentsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListIncidentsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListIncidentsResponseValidationError) ErrorName() string {
	return "ListIncidentsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListIncidentsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListIncidentsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListIncidentsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListIncidentsResponseValidationError{}

// Validate checks the field values on GetIncidentRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetIncidentRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetIncidentRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetIncidentRequestMultiError, or nil if none found.
func (m *GetIncidentRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetIncidentRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetId() <= 0 {
		err := GetIncidentRequestValidationError{
			field:  "Id",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetIncidentRequestMultiError(errors)
	}

	return nil
}

// GetIncidentRequestMultiError is an error wrapping multiple validation errors
// returned by GetIncidentRequest.ValidateAll() if the designated constraints
// aren't met.
type GetIncidentRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetIncidentRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetIncidentRequestMultiError) AllErrors() []error { return m }

// GetIncidentRequestValidationError is the validation error returned by
// GetIncidentRequest.Validate if the designated constraints aren't met.
type GetIncidentRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetIncidentRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetIncidentRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetIncidentRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetIncidentRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetIncidentRequestValidationError) ErrorName() string {
	return "GetIncidentRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetIncidentRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetIncidentRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetIncidentRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetIncidentRequestValidationError{}

// Validate checks the field values on GetIncidentResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetIncidentResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetIncidentResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetIncidentResponseMultiError, or nil if none found.
func (m *GetIncidentResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetIncidentResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetIncident()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetIncidentResponseValidationError{
					field:  "Incident",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetIncidentResponseValidationError{
					field:  "Incident",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetIncident()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetIncidentResponseValidationError{
				field:  "Incident",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetIncidentResponseMultiError(errors)
	}

	return nil
}

// GetIncidentResponseMultiError is an error wrapping multiple validation
// errors returned by GetIncidentResponse.ValidateAll() if the designated
// constraints aren't met.
type GetIncidentResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetIncidentResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetIncidentResponseMultiError) AllErrors() []error { return m }

// GetIncidentResponseValidationError is the validation error returned by
// GetIncidentResponse.Validate if the designated constraints aren't met.
type GetIncidentResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetIncidentResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetIncidentResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetIncidentResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetIncidentResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetIncidentResponseValidationError) ErrorName() string {
	return "GetIncidentResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetIncidentResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetIncidentResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetIncidentResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetIncidentResponseValidationError{}

// Validate checks the field values on UpdateIncidentStatusRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateIncidentStatusRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateIncidentStatusRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateIncidentStatusRequestMultiError, or nil if none found.
func (m *UpdateIncidentStatusRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateIncidentStatusRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetId() <= 0 {
		err := UpdateIncidentStatusRequestValidationError{
			field:  "Id",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := IncidentStatus_name[int32(m.GetStatus())]; !ok {
		err := UpdateIncidentStatusRequestValidationError{
			field:  "Status",
			reason: "value must be one of the defined enum values",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for ResolutionCategory

	// no validation rules for ResolutionNotes

	if len(errors) > 0 {
		return UpdateIncidentStatusRequestMultiError(errors)
	}

	return nil
}

// UpdateIncidentStatusRequestMultiError is an error wrapping multiple
// validation errors returned by UpdateIncidentStatusRequest.ValidateAll() if
// the designated constraints aren't met.
type UpdateIncidentStatusRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateIncidentStatusRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateIncidentStatusRequestMultiError) AllErrors() []error { return m }

// UpdateIncidentStatusRequestValidationError is the validation error returned
// by UpdateIncidentStatusRequest.Validate if the designated constraints
// aren't met.
type UpdateIncidentStatusRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateIncidentStatusRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateIncidentStatusRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateIncidentStatusRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateIncidentStatusRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateIncidentStatusRequestValidationError) ErrorName() string {
	return "UpdateIncidentStatusRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateIncidentStatusRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateIncidentStatusRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateIncidentStatusRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateIncidentStatusRequestValidationError{}

// Validate checks the field values on UpdateIncidentStatusResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateIncidentStatusResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateIncidentStatusResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateIncidentStatusResponseMultiError, or nil if none found.
func (m *UpdateIncidentStatusResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateIncidentStatusResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetIncident()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UpdateIncidentStatusResponseValidationError{
					field:  "Incident",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UpdateIncidentStatusResponseValidationError{
					field:  "Incident",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetIncident()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdateIncidentStatusResponseValidationError{
				field:  "Incident",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return UpdateIncidentStatusResponseMultiError(errors)
	}

	return nil
}

// UpdateIncidentStatusResponseMultiError is an error wrapping multiple
// validation errors returned by UpdateIncidentStatusResponse.ValidateAll() if
// the designated constraints aren't met.
type UpdateIncidentStatusResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateIncidentStatusResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateIncidentStatusResponseMultiError) AllErrors() []error { return m }

// UpdateIncidentStatusResponseValidationError is the validation error returned
// by UpdateIncidentStatusResponse.Validate if the designated constraints
// aren't met.
type UpdateIncidentStatusResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateIncidentStatusResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateIncidentStatusResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateIncidentStatusResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateIncidentStatusResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateIncidentStatusResponseValidationError) ErrorName() string {
	return "UpdateIncidentStatusResponseValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateIncidentStatusResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateIncidentStatusResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateIncidentStatusResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateIncidentStatusResponseValidationError{}

// Validate checks the field values on TriggerRCARequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *TriggerRCARequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TriggerRCARequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// TriggerRCARequestMultiError, or nil if none found.
func (m *TriggerRCARequest) ValidateAll() error {
	return m.validate(true)
}

func (m *TriggerRCARequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetId() <= 0 {
		err := TriggerRCARequestValidationError{
			field:  "Id",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return TriggerRCARequestMultiError(errors)
	}

	return nil
}

// TriggerRCARequestMultiError is an error wrapping multiple validation errors
// returned by TriggerRCARequest.ValidateAll() if the designated constraints
// aren't met.
type TriggerRCARequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TriggerRCARequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TriggerRCARequestMultiError) AllErrors() []error { return m }

// TriggerRCARequestValidationError is the validation error returned by
// TriggerRCARequest.Validate if the designated constraints aren't met.
type TriggerRCARequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TriggerRCARequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TriggerRCARequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TriggerRCARequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TriggerRCARequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TriggerRCARequestValidationError) ErrorName() string {
	return "TriggerRCARequestValidationError"
}

// Error satisfies the builtin error interface
func (e TriggerRCARequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTriggerRCARequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TriggerRCARequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TriggerRCARequestValidationError{}

// Validate checks the field values on TriggerRCAResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *TriggerRCAResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TriggerRCAResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// TriggerRCAResponseMultiError, or nil if none found.
func (m *TriggerRCAResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *TriggerRCAResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for RcaSummary

	// no validation rules for Cached

	if len(errors) > 0 {
		return TriggerRCAResponseMultiError(errors)
	}

	return nil
}

// TriggerRCAResponseMultiError is an error wrapping multiple validation errors
// returned by TriggerRCAResponse.ValidateAll() if the designated constraints
// aren't met.
type TriggerRCAResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TriggerRCAResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TriggerRCAResponseMultiError) AllErrors() []error { return m }

// TriggerRCAResponseValidationError is the validation error returned by
// TriggerRCAResponse.Validate if the designated constraints aren't met.
type TriggerRCAResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TriggerRCAResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TriggerRCAResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TriggerRCAResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TriggerRCAResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TriggerRCAResponseValidationError) ErrorName() string {
	return "TriggerRCAResponseValidationError"
}

// Error satisfies the builtin error interface
func (e TriggerRCAResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTriggerRCAResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TriggerRCAResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TriggerRCAResponseValidationError{}
