// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/stream/stream.proto

package streampb

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on SubscribeLogsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SubscribeLogsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SubscribeLogsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SubscribeLogsRequestMultiError, or nil if none found.
func (m *SubscribeLogsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *SubscribeLogsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ServiceName

	// no validation rules for Level

	// no validation rules for Fingerprint

	if len(errors) > 0 {
		return SubscribeLogsRequestMultiError(errors)
	}

	return nil
}

// SubscribeLogsRequestMultiError is an error wrapping multiple validation
// errors returned by SubscribeLogsRequest.ValidateAll() if the designated
// constraints aren't met.
type SubscribeLogsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SubscribeLogsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SubscribeLogsRequestMultiError) AllErrors() []error { return m }

// SubscribeLogsRequestValidationError is the validation error returned by
// SubscribeLogsRequest.Validate if the designated constraints aren't met.
type SubscribeLogsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SubscribeLogsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SubscribeLogsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SubscribeLogsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SubscribeLogsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SubscribeLogsRequestValidationError) ErrorName() string {
	return "SubscribeLogsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e SubscribeLogsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSubscribeLogsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SubscribeLogsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SubscribeLogsRequestValidationError{}

// Validate checks the field values on LogStreamEvent with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *LogStreamEvent) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on LogStreamEvent with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in LogStreamEventMultiError,
// or nil if none found.
func (m *LogStreamEvent) ValidateAll() error {
	return m.validate(true)
}

func (m *LogStreamEvent) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for EventType

	// no validation rules for Id

	// no validation rules for ServiceName

	// no validation rules for Level

	// no validation rules for Message

	// no validation rules for Fingerprint

	if all {
		switch v := interface{}(m.GetMetadata()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, LogStreamEventValidationError{
					field:  "Metadata",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, LogStreamEventValidationError{
					field:  "Metadata",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetMetadata()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return LogStreamEventValidationError{
				field:  "Metadata",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetOccurredAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, LogStreamEventValidationError{
					field:  "OccurredAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, LogStreamEventValidationError{
					field:  "OccurredAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetOccurredAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return LogStreamEventValidationError{
				field:  "OccurredAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return LogStreamEventMultiError(errors)
	}

	return nil
}

// LogStreamEventMultiError is an error wrapping multiple validation errors
// returned by LogStreamEvent.ValidateAll() if the designated constraints
// aren't met.
type LogStreamEventMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m LogStreamEventMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m LogStreamEventMultiError) AllErrors() []error { return m }

// LogStreamEventValidationError is the validation error returned by
// LogStreamEvent.Validate if the designated constraints aren't met.
type LogStreamEventValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e LogStreamEventValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e LogStreamEventValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e LogStreamEventValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e LogStreamEventValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e LogStreamEventValidationError) ErrorName() string { return "LogStreamEventValidationError" }

// Error satisfies the builtin error interface
func (e LogStreamEventValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sLogStreamEvent.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = LogStreamEventValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = LogStreamEventValidationError{}
