// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.26.1
// source: api/stream/stream.proto

package streampb

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubscribeLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,proto3" json:"service_name,omitempty"`
	Level         string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	Fingerprint   string                 `protobuf:"bytes,3,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeLogsRequest) Reset() {
	*x = SubscribeLogsRequest{}
	mi := &file_api_stream_stream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeLogsRequest) ProtoMessage() {}

func (x *SubscribeLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_stream_stream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeLogsRequest.ProtoReflect.Descriptor instead.
func (*SubscribeLogsRequest) Descriptor() ([]byte, []int) {
	return file_api_stream_stream_proto_rawDescGZIP(), []int{0}
}

func (x *SubscribeLogsRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *SubscribeLogsRequest) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *SubscribeLogsRequest) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

// LogStreamEvent is one frame pushed to the client over the SSE/WebSocket connection.
type LogStreamEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// event_type is "log" for normal entries or "anomaly" when a z-score spike is detected.
	EventType     string                 `protobuf:"bytes,1,opt,name=event_type,proto3" json:"event_type,omitempty"`
	Id            int64                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	ServiceName   string                 `protobuf:"bytes,3,opt,name=service_name,proto3" json:"service_name,omitempty"`
	Level         string                 `protobuf:"bytes,4,opt,name=level,proto3" json:"level,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Fingerprint   string                 `protobuf:"bytes,6,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,7,opt,name=metadata,proto3" json:"metadata,omitempty"`
	OccurredAt    *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=occurred_at,proto3" json:"occurred_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogStreamEvent) Reset() {
	*x = LogStreamEvent{}
	mi := &file_api_stream_stream_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogStreamEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogStreamEvent) ProtoMessage() {}

func (x *LogStreamEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_stream_stream_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogStreamEvent.ProtoReflect.Descriptor instead.
func (*LogStreamEvent) Descriptor() ([]byte, []int) {
	return file_api_stream_stream_proto_rawDescGZIP(), []int{1}
}

func (x *LogStreamEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *LogStreamEvent) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LogStreamEvent) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *LogStreamEvent) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogStreamEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogStreamEvent) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *LogStreamEvent) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *LogStreamEvent) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

var File_api_stream_stream_proto protoreflect.FileDescriptor

const file_api_stream_stream_proto_rawDesc = "" +
	"\n" +
	"\x17api/stream/stream.proto\x12\fpulse.stream\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"r\n" +
	"\x14SubscribeLogsRequest\x12\"\n" +
	"\fservice_name\x18\x01 \x01(\tR\fservice_name\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12 \n" +
	"\vfingerprint\x18\x03 \x01(\tR\vfingerprint\"\xa9\x02\n" +
	"\x0eLogStreamEvent\x12\x1e\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\n" +
	"event_type\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x03R\x02id\x12\"\n" +
	"\fservice_name\x18\x03 \x01(\tR\fservice_name\x12\x14\n" +
	"\x05level\x18\x04 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12 \n" +
	"\vfingerprint\x18\x06 \x01(\tR\vfingerprint\x123\n" +
	"\bmetadata\x18\a \x01(\v2\x17.google.protobuf.StructR\bmetadata\x12<\n" +
	"\voccurred_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\voccurred_at2\xac\x01\n" +
	"\rStreamService\x12\x9a\x01\n" +
	"\rSubscribeLogs\x12\".pulse.stream.SubscribeLogsRequest\x1a\x1c.pulse.stream.LogStreamEvent\"E\x92A+\n" +
	"\x06Stream\x12!Subscribe to real-time log stream\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/stream/logs0\x01B\x96\x01\x92Ax\x12\x17\n" +
	"\x10Pulse Stream API2\x031.0*\x02\x01\x022\x10application/json:\x10application/jsonZ5\n" +
	"3\n" +
	"\n" +
	"BearerAuth\x12%\b\x02\x12\x10Bearer JWT token\x1a\rAuthorization \x02Z\x19pulse/api/stream;streampbb\x06proto3"

var (
	file_api_stream_stream_proto_rawDescOnce sync.Once
	file_api_stream_stream_proto_rawDescData []byte
)

func file_api_stream_stream_proto_rawDescGZIP() []byte {
	file_api_stream_stream_proto_rawDescOnce.Do(func() {
		file_api_stream_stream_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_stream_stream_proto_rawDesc), len(file_api_stream_stream_proto_rawDesc)))
	})
	return file_api_stream_stream_proto_rawDescData
}

var file_api_stream_stream_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_stream_stream_proto_goTypes = []any{
	(*SubscribeLogsRequest)(nil),  // 0: pulse.stream.SubscribeLogsRequest
	(*LogStreamEvent)(nil),        // 1: pulse.stream.LogStreamEvent
	(*structpb.Struct)(nil),       // 2: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_api_stream_stream_proto_depIdxs = []int32{
	2, // 0: pulse.stream.LogStreamEvent.metadata:type_name -> google.protobuf.Struct
	3, // 1: pulse.stream.LogStreamEvent.occurred_at:type_name -> google.protobuf.Timestamp
	0, // 2: pulse.stream.StreamService.SubscribeLogs:input_type -> pulse.stream.SubscribeLogsRequest
	1, // 3: pulse.stream.StreamService.SubscribeLogs:output_type -> pulse.stream.LogStreamEvent
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_stream_stream_proto_init() }
func file_api_stream_stream_proto_init() {
	if File_api_stream_stream_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_stream_stream_proto_rawDesc), len(file_api_stream_stream_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_stream_stream_proto_goTypes,
		DependencyIndexes: file_api_stream_stream_proto_depIdxs,
		MessageInfos:      file_api_stream_stream_proto_msgTypes,
	}.Build()
	File_api_stream_stream_proto = out.File
	file_api_stream_stream_proto_goTypes = nil
	file_api_stream_stream_proto_depIdxs = nil
}
