// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.26.1
// source: api/ingest/ingest.proto

package ingestpb

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IngestLogRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	ServiceName string                 `protobuf:"bytes,1,opt,name=service_name,proto3" json:"service_name,omitempty"`
	// level must be one of: debug, info, warn, error, fatal
	Level   string `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	// metadata is arbitrary structured JSON forwarded to the log_entries.metadata JSONB column.
	Metadata      *structpb.Struct `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestLogRequest) Reset() {
	*x = IngestLogRequest{}
	mi := &file_api_ingest_ingest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestLogRequest) ProtoMessage() {}

func (x *IngestLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ingest_ingest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestLogRequest.ProtoReflect.Descriptor instead.
func (*IngestLogRequest) Descriptor() ([]byte, []int) {
	return file_api_ingest_ingest_proto_rawDescGZIP(), []int{0}
}

func (x *IngestLogRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *IngestLogRequest) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *IngestLogRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *IngestLogRequest) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type IngestLogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Fingerprint   string                 `protobuf:"bytes,2,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestLogResponse) Reset() {
	*x = IngestLogResponse{}
	mi := &file_api_ingest_ingest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestLogResponse) ProtoMessage() {}

func (x *IngestLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_ingest_ingest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestLogResponse.ProtoReflect.Descriptor instead.
func (*IngestLogResponse) Descriptor() ([]byte, []int) {
	return file_api_ingest_ingest_proto_rawDescGZIP(), []int{1}
}

func (x *IngestLogResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *IngestLogResponse) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

var File_api_ingest_ingest_proto protoreflect.FileDescriptor

const file_api_ingest_ingest_proto_rawDesc = "" +
	"\n" +
	"\x17api/ingest/ingest.proto\x12\fpulse.ingest\x1a\x1cgoogle/api/annotations.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x17validate/validate.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xd8\x01\n" +
	"\x10IngestLogRequest\x12.\n" +
	"\fservice_name\x18\x01 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x01\x18\xff\x01R\fservice_name\x12<\n" +
	"\x05level\x18\x02 \x01(\tB&\xfaB#r!R\x05debugR\x04infoR\x04warnR\x05errorR\x05fatalR\x05level\x12!\n" +
	"\amessage\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\amessage\x123\n" +
	"\bmetadata\x18\x04 \x01(\v2\x17.google.protobuf.StructR\bmetadata\"E\n" +
	"\x11IngestLogResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12 \n" +
	"\vfingerprint\x18\x02 \x01(\tR\vfingerprint2\x99\x01\n" +
	"\rIngestService\x12\x87\x01\n" +
	"\tIngestLog\x12\x1e.pulse.ingest.IngestLogRequest\x1a\x1f.pulse.ingest.IngestLogResponse\"9\x92A\x1c\n" +
	"\x06Ingest\x12\x12Ingest a log entry\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/ingest/logsB\xb9\x01\x92A\x9a\x01\x12\x17\n" +
	"\x10Pulse Ingest API2\x031.0*\x02\x01\x022\x10application/json:\x10application/jsonZW\n" +
	"U\n" +
	"\x06ApiKey\x12K\b\x02\x12:Tenant API key (hashed and matched against api_keys table)\x1a\tX-API-Key \x02Z\x19pulse/api/ingest;ingestpbb\x06proto3"

var (
	file_api_ingest_ingest_proto_rawDescOnce sync.Once
	file_api_ingest_ingest_proto_rawDescData []byte
)

func file_api_ingest_ingest_proto_rawDescGZIP() []byte {
	file_api_ingest_ingest_proto_rawDescOnce.Do(func() {
		file_api_ingest_ingest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_ingest_ingest_proto_rawDesc), len(file_api_ingest_ingest_proto_rawDesc)))
	})
	return file_api_ingest_ingest_proto_rawDescData
}

var file_api_ingest_ingest_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_ingest_ingest_proto_goTypes = []any{
	(*IngestLogRequest)(nil),  // 0: pulse.ingest.IngestLogRequest
	(*IngestLogResponse)(nil), // 1: pulse.ingest.IngestLogResponse
	(*structpb.Struct)(nil),   // 2: google.protobuf.Struct
}
var file_api_ingest_ingest_proto_depIdxs = []int32{
	2, // 0: pulse.ingest.IngestLogRequest.metadata:type_name -> google.protobuf.Struct
	0, // 1: pulse.ingest.IngestService.IngestLog:input_type -> pulse.ingest.IngestLogRequest
	1, // 2: pulse.ingest.IngestService.IngestLog:output_type -> pulse.ingest.IngestLogResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_ingest_ingest_proto_init() }
func file_api_ingest_ingest_proto_init() {
	if File_api_ingest_ingest_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_ingest_ingest_proto_rawDesc), len(file_api_ingest_ingest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_ingest_ingest_proto_goTypes,
		DependencyIndexes: file_api_ingest_ingest_proto_depIdxs,
		MessageInfos:      file_api_ingest_ingest_proto_msgTypes,
	}.Build()
	File_api_ingest_ingest_proto = out.File
	file_api_ingest_ingest_proto_goTypes = nil
	file_api_ingest_ingest_proto_depIdxs = nil
}
