// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/ingest/ingest.proto

package ingestpb

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on IngestLogRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *IngestLogRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on IngestLogRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// IngestLogRequestMultiError, or nil if none found.
func (m *IngestLogRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *IngestLogRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if l := utf8.RuneCountInString(m.GetServiceName()); l < 1 || l > 255 {
		err := IngestLogRequestValidationError{
			field:  "ServiceName",
			reason: "value length must be between 1 and 255 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := _IngestLogRequest_Level_InLookup[m.GetLevel()]; !ok {
		err := IngestLogRequestValidationError{
			field:  "Level",
			reason: "value must be in list [debug info warn error fatal]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetMessage()) < 1 {
		err := IngestLogRequestValidationError{
			field:  "Message",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetMetadata()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, IngestLogRequestValidationError{
					field:  "Metadata",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, IngestLogRequestValidationError{
					field:  "Metadata",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetMetadata()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return IngestLogRequestValidationError{
				field:  "Metadata",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return IngestLogRequestMultiError(errors)
	}

	return nil
}

// IngestLogRequestMultiError is an error wrapping multiple validation errors
// returned by IngestLogRequest.ValidateAll() if the designated constraints
// aren't met.
type IngestLogRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m IngestLogRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m IngestLogRequestMultiError) AllErrors() []error { return m }

// IngestLogRequestValidationError is the validation error returned by
// IngestLogRequest.Validate if the designated constraints aren't met.
type IngestLogRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e IngestLogRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e IngestLogRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e IngestLogRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e IngestLogRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e IngestLogRequestValidationError) ErrorName() string { return "IngestLogRequestValidationError" }

// Error satisfies the builtin error interface
func (e IngestLogRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sIngestLogRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = IngestLogRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = IngestLogRequestValidationError{}

var _IngestLogRequest_Level_InLookup = map[string]struct{}{
	"debug": {},
	"info":  {},
	"warn":  {},
	"error": {},
	"fatal": {},
}

// Validate checks the field values on IngestLogResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *IngestLogResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on IngestLogResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// IngestLogResponseMultiError, or nil if none found.
func (m *IngestLogResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *IngestLogResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Fingerprint

	if len(errors) > 0 {
		return IngestLogResponseMultiError(errors)
	}

	return nil
}

// IngestLogResponseMultiError is an error wrapping multiple validation errors
// returned by IngestLogResponse.ValidateAll() if the designated constraints
// aren't met.
type IngestLogResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m IngestLogResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m IngestLogResponseMultiError) AllErrors() []error { return m }

// IngestLogResponseValidationError is the validation error returned by
// IngestLogResponse.Validate if the designated constraints aren't met.
type IngestLogResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e IngestLogResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e IngestLogResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e IngestLogResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e IngestLogResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e IngestLogResponseValidationError) ErrorName() string {
	return "IngestLogResponseValidationError"
}

// Error satisfies the builtin error interface
func (e IngestLogResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sIngestLogResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = IngestLogResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = IngestLogResponseValidationError{}
